### ISSUE TITLE
Flask 0.12.4 pulls an incompatible version of Werkzeug (1.0.0)

### ISSUE THREAD

**Issue by bagerard** [pallets/flask#3501] opened 2020-02-12 18:59 UTC
Relates to https://stackoverflow.com/questions/60131900/weird-is-xhr-error-when-deploying-flask-app-to-heroku (which was viewed > 600 times in a few days)

### Expected Behavior
Flask pulls a compatible version of Werkzeug

```python
# Paste a minimal example that causes the problem.
```

### Actual Behavior
flask currently requires Werkzeug >= 0.15 but we recently noticed that some of our existing flask applications were broken. In fact we were (still) running flask 0.12.4 and as it is now it is pulling Werkzeug 1.0.0 which is incompatible (breaks at runtime).

```pytb
File "/app/server/controller.py", line 24, in get_kws 2020-02-08T22:31:05.893850+00:00 app[web.1]: 'query_results': query_result 2020-02-08T22:31:05.893850+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/json.py", line 298, in jsonify 2020-02-08T22:31:05.893851+00:00 app[web.1]: if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr: 2020-02-08T22:31:05.893851+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/werkzeug/local.py", line 347, in getattr 2020-02-08T22:31:05.893852+00:00 app[web.1]: return getattr(self._get_current_object(), name) 2020-02-08T22:31:05.893858+00:00 app[web.1]: AttributeError: 'Request' object has no attribute 'is_xhr'
```

As described in the SO post, upgrading flask >= 1.0 fixes this but I thought I'd still report this in case you think its worth releasing a 0.12.5, I could do the change in setup.py.

### Environment

* Python version: 3.8
* Flask version: 0.12.4
* Werkzeug version: 1.0

**Comment by davidism** [comment] 2020-02-12 19:12
Duplicate of #3493

**Closed** 2020-02-12 19:12 UTC
