### ISSUE TITLE
pycharm  No module named flask.flask    flask 1.1.0 

### ISSUE THREAD

**Issue by eic-aibee** [pallets/flask#3295] opened 2019-07-10 14:25 UTC
![企业微信截图_f4c6df24-39ee-40d7-9bc6-dcd6b60a2469](https://user-images.githubusercontent.com/37997057/60977048-584b5d00-a361-11e9-8a3e-29a183deb1e5.png)

![E38F8C81-7897-4A0A-B2A9-877517931A5C](https://user-images.githubusercontent.com/37997057/60977073-6305f200-a361-11e9-84b5-8724f2e20675.png)

when FLASK_DEBUG set to 1
debugger will report 

   No module named flask.flask

error

when i revert back flask version to 1.0.4, the error disappear.
I think this error is related new version. 
please fix it, thank you.

### Environment

* Python version: 3.7.2
* Flask version: 1.1.0

**Comment by ThiefMaster** [comment] 2019-07-10 14:32
Please provide some code to reproduce it (e.g. a cloneable git repo if it can't be done in a single file), ideally outside of PyCharm.

**Comment by davidism** [comment] 2019-07-10 14:55
Duplicate of #3293

**Closed by davidism** 2019-07-10 14:55 UTC

**Comment by cLupus** [comment] 2019-07-15 10:55
This seems to still be an issue in 1.1.1, with PyCharm. Or at the very least, I get the same error message.

**Comment by davidism** [comment] 2019-07-15 12:50
Requires a new release of Werkzeug

**Comment by tdiethe** [comment] 2019-07-23 20:34
I had the same issue, upgrading to werkzeug-0.15.5 fixed it for me

**Comment by paullim29** [comment] 2019-08-04 06:12
I have the same issue with it too:
Python 3.7.4
Flask 1.1.1
Werkzeug 0.15.5

But if I set the FLASK_ENV=production and turn off debug mode, it works

**Comment by simonloewe** [comment] 2019-08-13 11:38
make sure you import it like that:
`from flask import Flask` 
At least that worked for me.

**Comment by davidism** [comment] 2019-08-13 12:29
Duplicate of pallets/werkzeug#1614
