### ISSUE TITLE
app.test_client is not thread-safe

### ISSUE THREAD

**Issue by Zahlii** [pallets/flask#4990] opened 2023-02-21 09:47 UTC
Currently, using app.test_client() together with multi-threaded environment will fail:

```
from concurrent.futures import ThreadPoolExecutor

from flask import Flask, jsonify

app = Flask(__name__)


@app.route("/info")
def info():
    return jsonify({"status": "success"})


app.testing = True
with app.test_client() as client:

    def check(*args):
        return client.get("/info")

    with ThreadPoolExecutor(5) as tpe:
        print(tpe.map(check, range(5)))
```

with

```
Traceback (most recent call last):
  File "/Users/X/.pyenv/versions/flow-venv-3.9/lib/python3.9/site-packages/flask/ctx.py", line 399, in pop
    self.app.do_teardown_request(exc)
  File "/Users/X/.pyenv/versions/flow-venv-3.9/lib/python3.9/site-packages/flask/app.py", line 2370, in do_teardown_request
    for name in chain(request.blueprints, (None,)):
  File "/Users/X/.pyenv/versions/flow-venv-3.9/lib/python3.9/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()  # type: ignore[misc]
  File "/Users/X/.pyenv/versions/flow-venv-3.9/lib/python3.9/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.
```

Obviously, this can be solved by running the app as standalone (see http://www.prschmid.com/2013/01/multi-threaded-unit-test-for-flask-rest.html), but then I have to add manual error control and re-rise and do not get proper tracebacks while testing, and code coverage is also not given.

**Comment by davidism** [comment] 2023-02-21 14:19
Duplicate of #4734

Do not push the client globally around all tests, that's not the correct way to use it. Only push the client if you need to preserve the `request` global after a test request is evaluated, and _only_ around the code that needs it. In your example, you do not need to push the client at all, only created it.

```python
client = app.test_client()
```

**Closed by davidism** 2023-02-21 14:19 UTC

**Comment by Zahlii** [comment] 2023-02-21 14:31
Thanks for the feedback, so I'd need to make sure each test client is thread-local. Wouldn't it make sense to drop a hint for this somewhere in the documentation?
