### ISSUE TITLE
`Flask test` does not work (tables not created) after 2.2.0 update

### ISSUE THREAD

**Issue by probance-antoine** [pallets/flask#4728] opened 2022-08-02 13:24 UTC
With Flask 2.1.0 :

```bash
$ flask test
=========================================================================== test session starts ============================================================================
platform darwin -- Python 3.10.3, pytest-7.1.2, pluggy-1.0.0 -- /Users/antoine/Documents/Git/portail/venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/antoine/Documents/Git/portail
collected 29 items                                                                           
...
===================================================================== 29 passed, 5 warnings in 15.65s ======================================================================
```

With Flask 2.2.0 :

```bash
=========================================================================== test session starts ============================================================================
platform darwin -- Python 3.10.3, pytest-7.1.2, pluggy-1.0.0 -- /Users/antoine/Documents/Git/portail/venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/antoine/Documents/Git/portail
collected 29 items                                                                                                                                                         

test/test_accessibility.py::TestAccessibility::test_admin_accessibility ERROR
test/test_accessibility.py::TestAccessibility::test_client_accessibility ERROR
...
========================================================================= short test summary info ==========================================================================
ERROR test/test_accessibility.py::TestAccessibility::test_admin_accessibility - sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: cre_module
ERROR test/test_accessibility.py::TestAccessibility::test_client_accessibility - sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: cre_module
```

My tables are not created in Flask 2.2.0

However I didn't change anything in my tests and I don't see anything in the changelog that could affect the tests.
The errors happen only when I change the version of Flask (2.1.3 --> 2.2.0).

Here is the code that creates the tables (which works in 2.1.3 but not in 2.2.0).

```python
from portail import create_app
from portail.modules import PORTAIL_MODULES, detect_modules
from portail.database import db as _db
from portail.settings import TestConfig

@pytest.fixture()
def app():
    """An application for the tests."""
    _app = create_app(TestConfig())

    with _app.app_context():
        _db.create_all()
        modules = detect_modules()
        for m in modules:
            m.save(False)
        _db.session.commit()
        for m in modules:
            PORTAIL_MODULES[m.id] = m
            m.expunge()

    ctx = _app.test_request_context()
    ctx.push()

    yield _app

    ctx.pop()

    with _app.app_context():
        _db.drop_all()

@pytest.fixture()
def db(app):
    """A database for the tests."""
    _db.app = app
    with app.app_context():
        _db.create_all()

    yield _db

    # Explicitly close DB connection
    _db.session.close()
    _db.drop_all()
```

Has `app.app_context()` been modified or something I use for database setup?

Environment:

- Python version: 3.10.3
- Flask version: 2.2.0

**Comment by davidism** [comment] 2022-08-02 13:30
Duplicate of https://github.com/pallets/flask/issues/4725

**Closed by davidism** 2022-08-02 13:30 UTC
