### ISSUE TITLE
Example for teardown_appcontext in the docs out of sync with actual codebase

### ISSUE THREAD

**Issue by expobrain** [pallets/flask#3717] opened 2020-08-03 15:04 UTC
The documentation shows and example of a teardown function executed at the end of the app context https://flask.palletsprojects.com/en/1.1.x/appcontext/#storing-data.

The signature of the function decorated teardown function is `teardown_X()` but inspecting the codebase for Flask 1.1.x the function's signature must be `teardown_X(exception: Exception)` https://github.com/pallets/flask/blob/1.1.1/tests/test_appctx.py#L56.

I reckon that the documentation is out of sync.

### Environment

* Python version: 3.7
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by DKMDebugin** [comment] 2020-08-14 13:13
I reckon I can tackle this as my first contribution to this repo. @expobrain May I?

**Comment by davidism** [comment] 2020-08-14 16:41
No need to ask to work on an issue. As long as the issue is not assigned to anyone or have a linked open PR (both can be seen in the sidebar), anyone is welcome to work on any issue.

**Comment by DKMDebugin** [comment] 2020-08-14 21:44
Noted. Thanks. I want to run the changes by you before making a pull request @davidism 

```
from flask import g

    exception = Exception('Something went wrong!')

    def get_db():
        if 'db' not in g:
            g.db = connect_to_database()

        return g.db

    @app.teardown_appcontext
    def teardown_db(exception):
        db = g.pop('db', None)

        if db is not None:
            db.close()
```

**Closed** 2020-10-15 21:03 UTC
Labels: docs
