### ISSUE TITLE
url_for fails to use route parameters for non-POST routes during POST requests

### ISSUE THREAD

**Issue by antialiasis** [pallets/flask#2634] opened 2018-02-19 11:18 UTC
This is a bit of a weird one cropping up under very particular circumstances, but I spent a while last week puzzling over the issue. Probably best explained through the example.

---

### Expected Behavior

Entering "Todd" into the form field in this simple example app and submitting the form takes the user to /hello/Todd, just like clicking the "Click here if your name is Todd" link does.

```python
from flask import Flask, redirect, request, url_for
app = Flask(__name__)

@app.route("/")
def form():
    return """
        <p><a href="{}">Click here if your name is Todd</a><p>
        <form action="{}" method="post">
            <input type="text" name="name">
            <button type="submit">This is my name!</button>
        </form>
    """.format(
        url_for("hello", name="Todd"),
        url_for("hello")
    )

@app.route("/hello", methods=["GET", "POST"])
@app.route("/hello/<name>")
def hello(name=None):
    if request.method == "POST":
        return redirect(url_for("hello", name=request.form.get("name")))
    if name:
        return "Hello {}!".format(name)
    else:
        return "Hello World!"
```

### Actual Behavior

Submitting the form instead takes you to /hello?name=Todd.

Through my own testing I've concluded that `url_for("hello", name="Todd")` will return `/hello?name=Todd` if
- we are currently processing a POST request, _and_
- the target endpoint has a parameter-less route with the POST method allowed (`/hello`), _but_ the route we actually want (`/hello/<name>`) only allows GET requests.

This seems obviously bizarre and counterintuitive.

### Environment

* Python version: 3.6.4
* Flask version: 0.12.2
* Werkzeug version: 0.13

**Comment by ThiefMaster** [comment] 2018-02-19 12:13
Try passing `_method='GET'` to `url_for()`

**Comment by antialiasis** [comment] 2018-02-19 12:20
That does cause it to return the correct URL; however, I still don't think the displayed behaviour here makes any sense. The fact we're _currently_ processing a POST request does not in any way indicate that we should default to assuming we're going to make a POST request to any URL we happen to generate within the view function (quite the opposite, I'd think, since _most_ of the time in your average web app POST requests involve returning a redirect, which will be fetched with a GET request by the browser).

**Comment by davidism** [comment] 2018-02-23 22:57
Duplicate of #2469.

**Closed by davidism** 2018-02-23 22:57 UTC

**Comment by JulioJair** [comment] 2020-09-19 20:29
> Try passing `_method='GET'` to `url_for()`

Still not working for me.

I'm getting something like /hello?name=Todd
