### ISSUE TITLE
Error: Failed to find application in module "flaskr".  Are you sure it contains a Flask application?  Maybe you wrapped it in a WSGI middleware or you are using a factory function.

### ISSUE THREAD

**Issue by jxsoftyanlinyu** [pallets/flask#2703] opened 2018-04-16 05:24 UTC
click (6.7)
Flask (0.12.2)
flaskr (1.0.0, f:\python-flask\flask\examples\tutorial)
itsdangerous (0.24)
Jinja2 (2.10)
MarkupSafe (1.0)
pip (9.0.1)
setuptools (28.8.0)
Werkzeug (0.14.1)
(venv) PS F:\python-flask\flask\examples\tutorial> flask run
Usage: flask run [OPTIONS]

Error: Failed to find application in module "flaskr".  Are you sure it contains a Flask application?  Maybe you wrapped
it in a WSGI middleware or you are using a factory function.
(venv) PS F:\python-flask\flask\examples\tutorial>

**Comment by davidism** [comment] 2018-04-16 12:56
You didn't install the latest Flask master from GitHub. Duplicate of #2513.

**Closed by davidism** 2018-04-16 12:56 UTC
