### ISSUE TITLE
Python3.12.0b1 test_max_cookie_size error

### ISSUE THREAD

**Issue by arkamar** [pallets/flask#5146] opened 2023-05-29 06:22 UTC
`test_max_cookie_size` fails with python3.12, see the following error:
```
====================================================== FAILURES =======================================================
________________________________________________ test_max_cookie_size _________________________________________________

app = <Flask 'flask_test'>, client = <FlaskClient <Flask 'flask_test'>>, recwarn = WarningsRecorder(record=True)

    def test_max_cookie_size(app, client, recwarn):
        app.config["MAX_COOKIE_SIZE"] = 100

        # outside app context, default to Werkzeug static value,
        # which is also the default config
        response = flask.Response()
        default = flask.Flask.default_config["MAX_COOKIE_SIZE"]
        assert response.max_cookie_size == default

        # inside app context, use app config
        with app.app_context():
            assert flask.Response().max_cookie_size == 100

        @app.route("/")
        def index():
            r = flask.Response("", status=204)
            r.set_cookie("foo", "bar" * 100)
            return r

        client.get("/")
        for w in recwarn:
            print('---')
            print(w.message)
>       assert len(recwarn) == 1
E       assert 4 == 1
E        +  where 4 = len(WarningsRecorder(record=True))

app        = <Flask 'flask_test'>
client     = <FlaskClient <Flask 'flask_test'>>
default    = 4093
index      = <function test_max_cookie_size.<locals>.index at 0x7f4d8a84dbc0>
recwarn    = WarningsRecorder(record=True)
response   = <Response 0 bytes [200 OK]>
w          = <warnings.WarningMessage object at 0x7f4d8a90c560>

tests/test_basic.py:1868: AssertionError
------------------------------------------------ Captured stdout call -------------------------------------------------
---
ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
---
ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
---
Attribute s is deprecated and will be removed in Python 3.14; use value instead
---
The 'foo' cookie is too large: the value was 300 bytes but the header required 12 extra bytes. The final size was 312 bytes but the limit is 100 bytes. Browsers may silently ignore cookies larger than this.
```

I have only inserted 
```python
        for w in recwarn:
            print('---')
            print(w.message)
```
before `assert` to print the warnings. The same happens with flask-2.2.5 as well.

**Environment**:

- Python version: 3.12.0b1
- Flask version: 2.3.2 and 2.2.5

**Comment by davidism** [comment] 2023-05-29 06:30
Duplicate of https://github.com/pallets/werkzeug/issues/2704

**Closed by davidism** 2023-05-29 06:30 UTC
