### ISSUE TITLE
Potential backward incompatibilities brought by the werkzeug v1.0.0 update

### ISSUE THREAD

**Issue by haoyuanli** [pallets/flask#3482] opened 2020-02-06 23:27 UTC
### Expected Behavior

I don't have a concrete example yet, but Werkzeug today released a v1.0.0, and flask only specifies `Werkzeug>=0.15` as the dependency, that means any backware incompatible changes made to v1.0.0 of werkzeug could potentially break things here.

```python
```

### Actual Behavior

Things could be breaking

```pytb
```

### Environment

* Python version: 3.6.9
* Flask version: 1.1.1
* Werkzeug version: 1.0.0

If this is alright, then feel free to close this issue

**Comment by davidism** [comment] 2020-02-06 23:29
duplicate of #3481

**Closed by davidism** 2020-02-06 23:29 UTC
