### ISSUE TITLE
How to stop the server through code

### ISSUE THREAD

**Issue by chhongzh** [pallets/flask#4836] opened 2022-10-05 06:50 UTC
Hi,
I want to know how to stop server by code?

Does it provide a function like stop ()?

**Comment by davidism** [comment] 2022-10-05 13:21
Duplicate of https://github.com/pallets/werkzeug/issues/1752, see docs for how to manage a process https://werkzeug.palletsprojects.com/en/2.2.x/serving/#shutting-down-the-server

**Closed by davidism** 2022-10-05 13:21 UTC
