### ISSUE TITLE
I think it's a deadly bug in the Flask module.

### ISSUE THREAD

**Issue by gunyu1019** [pallets/flask#3801] opened 2020-10-21 14:12 UTC
### Expected Behavior
Normally, the "app.run()" should go back and open the web server with the port number 3000.

```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello Flask'

app.run(port=3000)
```

### Actual Behavior
Errors are occurring in "app.run()".
The same error occurs when using the debug tool in the visual studio code or the Python3 console window.

![Visual Studio Code traceback](https://user-images.githubusercontent.com/16767890/96731602-673d0e00-13f2-11eb-8e0f-93aada6e2285.png)
When using the debug tool in Visual Studio Code
![IDLE traceback](https://user-images.githubusercontent.com/16767890/96731788-99e70680-13f2-11eb-8621-4fefce6d519b.png)
When using the debug tool in IDLE

```pytb
Traceback (most recent call last):
  File "D:\Flask\start.py", line 8, in <module>
    app.run(port=3000)
  File "C:\Users\gunyu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "C:\Users\gunyu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\werkzeug\serving.py", line 1052, in run_simple
    inner()
  File "C:\Users\gunyu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\werkzeug\serving.py", line 996, in inner
    srv = make_server(
  File "C:\Users\gunyu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\werkzeug\serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "C:\Users\gunyu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\werkzeug\serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "C:\Users\gunyu\AppData\Local\Programs\Python\Python38-32\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\gunyu\AppData\Local\Programs\Python\Python38-32\lib\http\server.py", line 140, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Users\gunyu\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
```

### Environment

* Python version: v3.8.2
* Flask version: v1.1.2
* Werkzeug version: v1.0.1

**Comment by ThiefMaster** [comment] 2020-10-21 14:14
duplicate of #3484 i think

**Closed by ThiefMaster** 2020-10-21 14:14 UTC
