### ISSUE TITLE
Documentation: "flask --app hello run --debug"  no longer works

### ISSUE THREAD

**Issue by trent-shipley** [pallets/flask#4931] opened 2022-12-29 16:25 UTC
The vanilla command to activate the development server is documented as:

$ flask --app hello run --debug 

on 

https://flask.palletsprojects.com/en/2.2.x/server/   copyright 2010 (Really, no changes since 2010?)

no longer works.  Specifically the '--debug' option seems to be obsolete.

$ flask run --help     says use

--debugger / --no-debugger  and strongly implies that the debugger is on by default (although there is room for a different interpretation).

The web page and help are not aligned.

Replication:

$ flask --app flasker run --debug    produces an error

$ flask --app flaskr run --debugger   starts the development server.

I did not check if the debugger is on by default

Describe the expected behavior that should have happened but didn't:

Per https://flask.palletsprojects.com/en/2.2.x/server/  

$ flask --app hello run --debug

should start the development server.

Environment:

- Python version: 3.11.0
- Flask version:  2.2.2
- Werkzeug: 2.2.2
- Windows: Microsoft Windows 11 Pro, 10.0.22623 Build 22623

**Comment by davidism** [comment] 2022-12-29 17:44
Duplicate of #4928, #4930.#4930 

> Really, no changes since 2010?

A year in a copyright notice is not a last updated timestamp.

**Closed by davidism** 2022-12-29 17:44 UTC
