### ISSUE TITLE
No TLS listener with flask run

### ISSUE THREAD

**Issue by snobu** [pallets/flask#2612] opened 2018-01-30 15:48 UTC
Is `flask run` supposed to spin up a TLS listener if the app is configured with TLS?

Take this `app.py`:

```python
if __name__ == "__main__":
    app.run(ssl_context=('cert.pem', 'key.pem'))
```

- If i run `python app.py` i get the expected `Listening on https://...` and all is well - note the http**s**.
- If i run `flask run` i get an HTTP listener, `Listening on http://...`. No TLS.

Is this expected behaviour? May i suggest mentioning this somewhere in the quickstart? - http://flask.pocoo.org/docs/0.12/quickstart/

Would be great if someone would lay out the difference between the two invocations.

Ref:
https://stackoverflow.com/questions/48518584/

**Comment by davidism** [comment] 2018-01-30 15:56
Duplicate of #2606. And your SO question is a duplicate of https://stackoverflow.com/q/48467835/400617.

**Closed by davidism** 2018-01-30 15:56 UTC

**Comment by davidism** [comment] 2018-01-30 16:01
Surprising that it's come up twice so recently after the issue and PR were made. Also, sorry, thought the question was yours originally, but you were the one hunting down an MCVE from them. Thanks for the help. :-)

**Comment by snobu** [comment] 2018-01-30 16:04
No worries, glad this is no longer an issue with Flask 1.0+. Can one already get that from pip or there's an ETA?
