### ISSUE TITLE
Flask not handling POST data in some circumstances

### ISSUE THREAD

**Issue by djjudas21** [pallets/flask#5168] opened 2023-06-20 20:07 UTC
I am trying to use Flask as a lightweight webserver to accept data from a WiFi-enabled weather station, which makes an HTTP POST request every 60 seconds. I captured the request using an http echo server:

```json
{
    "path": "/report",
    "headers": {
        "host": "192.168.0.65",
        "connection": "Close",
        "content-type": "application/x-www-form-urlencoded",
        "content-length": "493"
    },
    "method": "POST",
    "body": "PASSKEY=573AF40DB42C66057D20631F706CD585&stationtype=EasyWeatherPro_V5.1.1&runtime=1&dateutc=2023-06-20+14:56:02&tempinf=73.4&humidityin=49&baromrelin=29.917&baromabsin=29.536&tempf=72.5&humidity=58&winddir=251&windspeedmph=1.12&windgustmph=2.24&maxdailygust=9.17&solarradiation=293.99&uv=2&rainratein=0.000&eventrainin=0.638&hourlyrainin=0.000&dailyrainin=0.638&weeklyrainin=0.650&monthlyrainin=0.650&yearlyrainin=0.650&totalrainin=0.650&wh65batt=0&freq=868M&model=WS2900_V2.01.18&interval=60",
    "fresh": false,
    "hostname": "192.168.0.65",
    "ip": "::ffff:10.1.199.64",
    "ips": [],
    "protocol": "http",
    "query": {},
    "subdomains": [],
    "xhr": false,
    "os": {
        "hostname": "http-webhook-6675856576-j2jzb"
    },
    "connection": {}
}
```

I made a `curl` command so I could simulate these POST requests for development & testing:

```
curl -d "PASSKEY=573AF40DB42C66057D20631F706CD585&stationtype=EasyWeatherPro_V5.1.1&runtime=1&dateutc=2023-06-20+14:56:02&tempinf=73.4&humidityin=49&baromrelin=29.917&baromabsin=29.536&tempf=72.5&humidity=58&winddir=251&windspeedmph=1.12&windgustmph=2.24&maxdailygust=9.17&solarradiation=293.99&uv=2&rainratein=0.000&eventrainin=0.638&hourlyrainin=0.000&dailyrainin=0.638&weeklyrainin=0.650&monthlyrainin=0.650&yearlyrainin=0.650&totalrainin=0.650&wh65batt=0&freq=868M&model=WS2900_V2.01.18&interval=60" -X POST http://192.168.0.65:8080/report
```

Using the `curl` command, I developed my simple application. The main part of the app grabs all the keys to process them.

```py
@app.route('/report', methods=['POST'])
def logEcowitt():

    # Retrieve the POST body
    data = request.form

    for key in data:
        value = data[key]
```

This worked fine when I tested it with my `curl` command - all the keys and values were available. However, when I tested the app with the real data from the weather station, `request.form` had an empty value of `ImmutableMultiDict([])`. I double checked that the POST data was still there, and it was.

So I changed my app logic to parse the parameters manually:

```py
@app.route('/report', methods=['POST'])
def logEcowitt():

    for field in request.get_data(as_text=True).split('&'):
        [key, value] = field.split('=')
```

But I found that `request.get_data(as_text=True)` was an empty string. Both of these methods of parsing POST data work normally 

I think this will be hard to replicate because the weather station is in my house and I haven't (yet) found a way of recreating the problem with `curl`. Is there a way I can turn up the debugging?I'm also going to experiment with other versions of Flask to see if this behaviour is a regression.

Thanks

Environment:

- Python version: 3.11
- Flask version: 2.3.2

**Comment by davidism** [comment] 2023-06-20 20:32
Duplicate of https://github.com/pallets/werkzeug/issues/2734. I have no way to reproduce the error, so I can't say what the issue is. It sounds like there's a problem with how this service is sending data.

**Closed by davidism** 2023-06-20 20:32 UTC

**Comment by davidism** [comment] 2023-06-20 20:39
You can use a tool like https://smee.io/ to capture the webhook request and forward/resend it to a local instance of your app. Use a debugger to set a breakpoint in `run_wsgi` and step through the code. Look at `request.environ` very early, try reading from `request.environ["wsgi.input"]`, etc. to see if there is data even early on.
