### ISSUE TITLE
Debugging during bootstrapping

### ISSUE THREAD

**Issue by der-Daniel** [pallets/flask#2225] opened 2017-03-27 21:50 UTC
Hi,

when I start my `Flask` app via `python3 -m flask run` and there is an error in my code, `Flask` only returns with the following message:

    Usage: python -m flask run [OPTIONS]
    
    Error: The file/path provided (server2.run) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py

Is there a way to get proper error stack messages or am I not seeing the obvious.. :thinking: 

~ For Frodo

**Comment by ThiefMaster** [comment] 2017-03-27 21:50
duplicate of #2214?

**Comment by untitaker** [comment] 2017-03-27 22:54
No, but it will be in the next release. You can use `pip install -U git+https://github.com/pallets/flask` in the meantime.

**Closed by untitaker** 2017-03-27 22:54 UTC
