### ISSUE TITLE
app.run(port='5000', debug=True) error

### ISSUE THREAD

**Issue by trigremm** [pallets/flask#2220] opened 2017-03-23 10:46 UTC
Inappropriate  behaviour in app.run function with debug set to True and False

```app.run(port='5000', debug=False)``` runs perfectly 

however when debug=True

```app.run(port='5000', debug=True)``` it throws error 
```python3 hello_world.py 
Traceback (most recent call last):
  File "hello_world.py", line 13, in <module>
    app.run(port='5000', debug=True)
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3.5/site-packages/werkzeug/serving.py", line 717, in run_simple
    s.bind((hostname, port))
TypeError: an integer is required (got type str)```

**Comment by ThiefMaster** [comment] 2017-03-23 10:47
Ports are numbers, not strings. However, I agree that it'd be nicer to fail in both cases.

**Comment by aaossa** [comment] 2017-03-24 12:49
Can I submit a PR for this? I may have time this weekend. But, of course, if you want to do it you can go with it :) 

Maybe a good solution is to check types and raise TypeError?

**Comment by untitaker** [comment] 2017-03-24 12:50
@aaossa Yes and yes. Also please add a test :)

**Comment by aaossa** [comment] 2017-03-24 23:59
@untitaker, @ThiefMaster 

Reading the source code, I thought, **is this Werkzeug or Flask responsability?** The error from the OP comment is raised from `werkzeug.serving`, because `run_simple` is from that module. We could check types after [flask/app.py#L843](https://github.com/pallets/flask/blob/master/flask/app.py#L843) to avoid this problem without relying in Werkzeug. But we have another option: apply the same check at the top of `run_simple` ([werkzeug/serving.py#L602](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L602)) to (also) avoid the same error when using Werkzeug but not Flask.

**Why does the same code work when using `debug=False`?** Because debug mode uses the reloader (so [`use_reloader` is set to `True`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L701)) and Werkzeug tries to [use a socket without explicitly converting `port` to `int`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L717). When using `debug=False`, `use_reloader` is `False` and Werkzeug [calls an inner function that uses `make_server`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L693). The difference in this behaviour is because [`BaseWSGIServer` uses  `int(port)`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L501), explicitly converting the `port` from `str` to `int`.

IMO, if Werkzeug is suposed to allow using a string value in `port` then we should explicitly convert the `port` parameter, when possible, and raise an exception when needed. If Werkzeug is not supposed to allow this behaviour, then Flask should allow `int`s only (and Werkzeug should do it too)

---

PS: I could make a PR in both repositories if needed. I'm asking because you are maintainers of both projects and I think both projects deserve a good solution :ok_hand:

**Comment by untitaker** [comment] 2017-03-25 00:13
I think it would be good to do this check in Werkzeug's make_server such that it is independent of reloader.

On 25 March 2017 00:59:46 CET, Antonio Ossa <notifications@github.com> wrote:
>@untitaker, @ThiefMaster 
>
>Reading the source code, I thought, **is this Werkzeug or Flask
>responsability?** The error from the OP comment is raised from
>`werkzeug.serving`, because `run_simple` is from that module. We could
>check types after
>[flask/app.py#L843](https://github.com/pallets/flask/blob/master/flask/app.py#L843)
>to avoid this problem without relying in Werkzeug. But we have another
>option: apply the same check at the top of `run_simple`
>([werkzeug/serving.py#L602](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L602))
>to (also) avoid the same error when using Werkzeug but not Flask.
>
>**Why does the same code work when using `debug=False`?** Because debug
>mode uses the reloader (so [`use_reloader` is set to
>`True`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L701))
>and Werkzeug tries to [use a socket without explicitly converting
>`port` to
>`int`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L717).
>When using `debug=False`, `use_reloader` is `False` and Werkzeug [calls
>an inner function that uses
>`make_server`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L693).
>The difference in this behaviour is because [`BaseWSGIServer` uses 
>`int(port)`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L501),
>explicitly converting the `port` from `str` to `int`.
>
>IMO, if Werkzeug is suposed to allow using a string value in `port`
>then we should explicitly convert the `port` parameter, when possible,
>and raise an exception when needed. If Werkzeug is not supposed to
>allow this behaviour, then Flask should allow `int`s only (and Werkzeug
>should do it too)
>
>---
>
>PS: I could make a PR in both repositories if needed. I'm asking
>because you are maintainers of both projects and I think both projects
>deserve a good solution :ok_hand: 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/2220#issuecomment-289170586

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aaossa** [comment] 2017-03-25 02:18
But the problem is not in `make_server` only, a check here won't fix this. An exception in `make_server` will be raised only when using `debug=False`, but the behaviour with `debug=True` will be the same. I think we should add the check in Werkzeug's `run_simple`.

**Comment by untitaker** [comment] 2017-03-25 20:06
Right, forgot about that! `run_simple` it is then.

**Closed** 2017-03-27 21:36 UTC
