### ISSUE TITLE
route decorator compatibility with MethodView

### ISSUE THREAD

**Issue by codectl** [pallets/flask#4994] opened 2023-02-23 10:04 UTC
I am trying to get the ```route``` decorator to work with the ```MethodView```.

```python
from flask import Blueprint
from flask.views import MethodView

api = Blueprint("api", __name__)

@api.route("/users")
class UserAPI(MethodView):

    def get(self):
        pass

    def post(self):
        pass
```

I am not sure if this is currently supported but it would be a good plus.

**Comment by RonnyPfannschmidt** [comment] 2023-02-23 12:29
based on the examples of views its not  plus - the idea behind views is that one can configure and instaniate them

if no configuration was needed, one could just set up one blueprint, no need for a view class

**Comment by davidism** [comment] 2023-02-23 13:47
Duplicate of #3404, #3975, #4817

Register blueprints with `app.add_url_rule("/path", endpoint="name", view_func=View.as_view())`. I do not plan to allow using `@app.route` on `View` classes, as it would prevent passing args and kwargs to `as_view`, and would be a special case over any other API extension. Extensions are free to provide whatever methods they like for defining an API.

**Closed by davidism** 2023-02-23 13:47 UTC
