### ISSUE TITLE
session.new is never true

### ISSUE THREAD

**Issue by d-ganchar** [pallets/flask#2564] opened 2017-12-19 13:37 UTC
According to the [documentation](http://flask.pocoo.org/docs/0.12/api/#flask.session.new), **new** attribute returns **True** if the session is new. Otherwise **False**, but it's not like that. How to reproduce:

```
from flask import Flask, session

app = Flask(__name__)
app.config["SECRET_KEY"] = "thisisasecret"
app.config['SESSION_TYPE'] = 'filesystem'

@app.route("/")
def index():
    if 'user_id' not in session:
        session['user_id'] = 'jon'
    print(session.new)
    print(session.modified)
    return 'testing sessions'
# just for debugging
@app.route("/clear")
def clear():
    session.clear()
    return 'clear'

if __name__ == "__main__":
    app.run(debug=True)
```

Run app and call _/_ endpoint twice. Output:

```
127.0.0.1 - - [19/Dec/2017 16:18:20] "GET /clear HTTP/1.1" 200 -
False # value of session.new
True
127.0.0.1 - - [19/Dec/2017 16:18:25] "GET / HTTP/1.1" 200 -
False # value of session.new
False
```

As I Understood when we initialize session, **session.new** should return **True**(when we call endpoint at first time). Is it right?

### Environment

* Python version: 2.7.13
* Flask version: 0.12.2
* Werkzeug version: 0.13

[Link](https://stackoverflow.com/questions/47885251/unexpected-working-of-new-attribute-of-session-class-in-flask) to question on SO

**Comment by davidism** [comment] 2017-12-19 14:20
From the [code](https://github.com/pallets/flask/blob/a43a439c7a839edc8c5ac7062acb694eceb99e55/flask/sessions.py#L37-L40):

    #: some session backends can tell you if a session is new, but that is
    #: not necessarily guaranteed.  Use with caution.  The default mixin
    #: implementation just hardcodes ``False`` in.
    new = False

**Comment by pawel1830** [comment] 2017-12-20 11:16
@davidism So it's not a bug, it's a feature?

**Comment by davidism** [comment] 2017-12-20 13:24
It's not implemented for the default cookie session.

**Comment by davidism** [comment] 2018-01-04 21:00
Closing, see discussion at #2579. Updated documentation at #2580.

**Closed by davidism** 2018-01-04 21:00 UTC
