### ISSUE TITLE
Cant Run a flask server with FLASK_ENV=development or production

### ISSUE THREAD

**Issue by Riprock** [pallets/flask#3313] opened 2019-07-23 20:30 UTC
### Expected Behavior
Should be able to run flask with FLASK_ENV=development or production

### Actual Behavior
I get the output
 * Serving Flask app "simple" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
c:\users\Riprock\Projects\simple s&r\venv\scripts\python.exe: No module named C:\Users\Riprock\Projects\Simple S&R\venv\Scripts\flask

### Environment

* Python version: 3.7.4
* Flask version: 1.1.1
* Werkzeug version:  0.15.5

I can't seem to get a flask server running after updating to the latest version of Flask and python. Before the update my FLASK_ENV=development and FLASK_DEBUG=1. Then I updated and started to encounter the error. I tried rebuilding my venv and getting the same error.

**Comment by davidism** [comment] 2019-07-23 20:59
Duplicate of pallets/werkzeug#1614

**Closed by davidism** 2019-07-23 20:59 UTC

**Comment by Azzzizzz** [comment] 2020-05-23 09:33
Just prefix with "set" for windows and "export" for OSX.
Example: set FLASK_ENV=development 
Then, flask run
