### ISSUE TITLE
flask.send_file() with Pylance in strict mode shows reportUnknownMemberType

### ISSUE THREAD

**Issue by bra1nDeaD** [pallets/flask#5320] opened 2023-11-03 22:23 UTC
I was using this method fine, until I switched on 'strict' mode in the Pylance plugin for vscode. This gave me the error at calling the method:

```
Type of "send_file" is partially unknown
  Type of "send_file" is "(path_or_file: PathLike[Unknown] | str | BinaryIO, mimetype: str | None = None, as_attachment: bool = False, download_name: str | None = None, conditional: bool = True, etag: bool | str = True, last_modified: datetime | int | float | None = None, max_age: int | ((str | None) -> (int | None)) | None = None) -> Response" 
```
Code that causes the error:
```
@app.route('/')
def home():
    return flask.send_file('web/index.html')
```
The error sits on: "flask.send_file"

I've been trying to infer this type and googled around, but can't seem to resolve this issue. having investigated "PathLike[Unknown]" for a while now looking into this, I've come to the conclusion that this issue is likely cause by the fact that PathLike requires a generic type to be declared.  If I manually (and temporary) add this generic type in, the error goes away.

In helpers.py (around line 391) I change:
```
def send_file(
    path_or_file: t.Union[os.PathLike, str, t.BinaryIO],
```
into:
```
def send_file(
    path_or_file: t.Union[os.PathLike[str], str, t.BinaryIO],
```
I've added the "[str]" generic type to PathLike. Possibly this might need to be "[AnyStr]" as that is the type declared in os.

I hope this is an easy fix, and that this isn't a user error that I have mistaken as an issue.

Environment:
Python 3.11.2
Flask 2.2.2
Werkzeug 2.2.2

**Comment by davidism** [comment] 2023-11-03 22:51
This sounds reasonable. Happy to review a PR.

**Comment by dannyi96** [comment] 2023-11-12 23:52
take

**Comment by dannyi96** [comment] 2023-11-12 23:57
take

**Comment by davidism** [comment] 2023-11-12 23:59
Hey, thanks for being interested! Here, in our project, there's no need to ask to work on an issue. As long as the issue is not assigned to anyone and doesn't have have a linked open PR (both can be seen in the sidebar), anyone is welcome to work on any issue. So please go ahead! If you need help, you can ask here or on [our Discord server](https://discord.gg/pallets).

**Closed** 2023-11-15 20:59 UTC
Labels: typing
