### ISSUE TITLE
Flask send 400 "Bad Request Version" 

### ISSUE THREAD

**Issue by ballzb** [pallets/flask#4543] opened 2022-04-16 01:39 UTC
Flask will send 400 "Bad Request Version" if Flask send 401 or 403 response to Client without closing the http connection.

1. Client POST text/xml message without "Basic Authorization"
2. Server response 401, but don't send "HTTP: close"
3. Client POST text/xml message again with "Basic Authorization"
4. Server response 400 "Bad Request Version"

I wish Flask can handle the second POST correctly, And I have tested using another server, it works well.
Please the capture for details. And the partial code is as following(full code link:https://github.com/ballzb/pyacs )

```python
@basic_auth.verify_password
def verify_password(username, password):
    #app.logger.error(f"username={username}, password={password}")
    if username==config['local']['username'] and password==config['local']['password']:
        return username
    else:
        g.current_user = username
        return False #username or password error

@basic_auth.error_handler
def auth_error(status_code):
    #app.logger.error(f"status_code={status_code}, username={g.current_user}")
    if status_code == 401:
        if g.current_user:
            return cwmp.make_403_response()
        else:
            return cwmp.make_401_response(config['local']['authentication'])
    # return "Access Denied", status_code


@app.route('/acs', methods=['GET', 'POST'])
@multi_auth.login_required
def acs():
    """ main tr069/acs entry point """
    if request.method == 'GET':
        return DESCRIPTION

    if request.method != 'POST':
        return 'There is nothing to show'

    #app.logger.error(request.headers)


    # POST requests
    if request.content_type.find('text/xml')==-1:
        app.logger.error(f"request.content_type={request.content_type}")
        return 'Wrong content type'

    result = cwmp.handle_request(request)
    if result:
        return result
    else:
        return DESCRIPTION
```

Environment:

- Python version: 3.10
- Flask version: 2.1.1
[400.zip](https://github.com/pallets/flask/files/8499045/400.zip)

**Comment by ballzb** [comment] 2022-04-16 02:22
I have tried to start server using waitress, but I got "Connection is a "hop-by-hop" header; it cannot be used by a WSGI application (see PEP 3333)". Is this related to this bug?

**Comment by davidism** [comment] 2022-04-16 05:03
Duplicate of https://github.com/pallets/flask/issues/4507, https://github.com/pallets/werkzeug/issues/2380, etc.

**Closed by davidism** 2022-04-16 05:03 UTC
