### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\x90' in file flask.exe

### ISSUE THREAD

**Issue by kiven517** [pallets/flask#2543] opened 2017-12-06 09:49 UTC
### Expected Behavior

In flask website use tutorials, in the third step ` flask run ` to run my web, appear this mistake.
In py files line first, I use the ` # - coding: utf-8 -- ` specified utf-8.
I'm writing code in Pycharm. Start the web with the CMD run command.
I copy the project directory into ubuntu and it works.
No related problems were found on the Internet.
Please give us some ideas and solve this problem.
thank you

Below is a screenshot of the Pycharm

![](http://ono3vb8rf.bkt.clouddn.com/FiQ9vFgwM9dNrd29zW0gHiFNUUs8.png)

Tell us what should happen.

```shell
kevin@DESKTOP-5KM5T43:~/workspaces/flaskr$ flask run
 * Serving Flask app "flaskr"
 * Forcing debug mode on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 244-441-781
```

### Actual Behavior

Tell us what happens instead.

```pytb
D:\workspace\development\python\WebProject\flaskr>flask run
 * Serving Flask app "flaskr"
 * Forcing debug mode on
 * Restarting with stat
  File "D:\ProgramData\Anaconda3\Scripts\flask.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file D:\ProgramData\Anaconda3\Scripts\flask.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

### Environment

* Operating system

```
OS name: Microsoft Windows 10 professional edition
OS version: 10.0.16299 temporary lack of Build 16299
```

* Python version:

```
D:\workspace\development\python\WebProject\flaskr>python --version
Python 3.6.3 :: Anaconda, Inc.
```

* Flask version:

```
D:\workspace\development\python\WebProject\flaskr>python -m flask --version
Flask 0.12.2
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
```

* Werkzeug version:

```
Werkzeug (0.12.2)
```

**Comment by greyli** [comment] 2017-12-08 03:47
Duplicate of [pallets/werkzeug#1136](https://github.com/pallets/werkzeug/issues/1136).

**Comment by greyli** [comment] 2017-12-08 03:50
Currently you can use `python -m flask run`, until the bug was fixed.

**Closed** 2017-12-08 03:55 UTC

**Comment by kiven517** [comment] 2017-12-08 04:52
@greyli Thank you very much. its working

**Comment by 1992Zz** [comment] 2019-01-16 08:17
> 
> 
> Currently you can use `python -m flask run`, until the bug was fixed.

Could you tell me more about it?
