### ISSUE TITLE
url_for uses _request_ctx for its choice of default_methods, this seems wrong

### ISSUE THREAD

**Issue by jeffrey** [pallets/flask#2469] opened 2017-09-08 20:32 UTC
In response to a POST, I wanted to construct a URL pointing at a different URL (the home of the created object) which did NOT support POST.

It turns out, this doesn't work with Flask==0.12.2. The rule I want doesn't match, so I end up matching a less specific rule, with the distinguishing name treated as a parameter, not a path.

What appears to be happening is that default method is being pulled out of _request_ctx early in url_for(). In this case, that method will be a POST.

I'm not sure if defaulting to the request's current method is really desirable. How often are you responding to a POST and want url_for to respond with the best match for POST? I think typically most endpoints will respond to a GET, but many endpoints won't respond to a POST.

The workaround is to include the undocumented _method keyword argument. That will work (hopefully permanently), but I'd prefer:

A) for this to be explicitly supported by the API, and
B) I think the default should probably always be GET. My guess is that will be correct far more

**Comment by nitingupta89** [comment] 2017-10-10 05:51
@jeffrey Could you please elaborate with example?

**Comment by jesseops** [comment] 2017-10-12 14:44
The described issue specifically occurs within the werkzeug codebase: https://github.com/pallets/werkzeug/blob/40bfd13b4383512160a139aea3721c3746a4d7ae/werkzeug/routing.py#L1334

Each request has a request context built for it, along with a new URL adapter instance (ie a `Map` bound to the environment of that request). werkzeug specifically extracts the `REQUEST_METHOD` from `request.environ` and passes that to `Map.bind` to set the default method for matching URLs.

As for the "undocumented" `_method` arguments, it's very clearly documented as a parameter to `url_for`: http://flask.pocoo.org/docs/0.12/api/#flask.url_for

**Comment by davidism** [comment] 2017-10-12 14:57
Thanks @jesseops. Closing this as I think the current behavior and documentation is appropriate.

**Closed by davidism** 2017-10-12 14:57 UTC

**Comment by antialiasis** [comment] 2018-02-24 00:16
Can I ask about the rationale for considering the current behaviour appropriate? It's surprising (why would anyone expect this?), unhelpful (as Jeffrey mentioned, how often are you processing a POST request and want to generate a URL to send another POST request to? I'm willing to bet that if anything it's less likely than wanting that while processing a GET request), and quite difficult to debug to boot, since there's no error, just a function that one would expect to behave consistently suddenly turning out to return different things based on tenuously related application state. I tested a lot of different things before coming to the conclusion the current HTTP method was the issue.

At the absolute least, the fact it does depend on that state ought to be documented. The documentation for the _method argument says "if provided this explicitly specifies an HTTP method"; at least to me, this implies the default is to not specify a particular method, not that the default is equivalent to specifying whichever HTTP method the current request is. There is nothing suggesting the output of the function depends on the current HTTP method of all things.

**Comment by jesseops** [comment] 2018-02-26 05:52
I agree that the first line of the documentation for `url_for` could be worded more clearly.

Current:
> Generates a URL to the given endpoint with the method provided.

Could be reworded:
> Generates a URL to the given endpoint. The current HTTP method is used by default; this may be overridden by passing the `_method` parameter.

I'm willing to open a PR if that wording is acceptable to make the behavior clear and more immediately obvious.

One question @davidism might be able to clear up; is there a reason `_method` has a leading underscore? When I see that I assume it's not truly intended as a public parameter.

**Comment by davidism** [comment] 2018-02-26 12:57
Because there could be a URL capture with that name.

**Comment by mattfabina** [comment] 2018-10-23 09:20
+1 for reconsidering documentation and/or behavior.

Ran into this issue "in the wild" and went through the usual debugging steps and eventually ended up here. This cost me a bit of time.

For what it's worth, here's my minimal reproduction code:

```python
import flask


app = flask.Flask(__name__)


@app.route('/good/')
@app.route('/good/<good_id>')
def good(good_id='my_good_id'):
    # url == /good/my_good_id
    url = flask.url_for('good', good_id=good_id)
    print(url)
    return url


@app.route('/bad/')
@app.route('/bad/<bad_id>', methods=['POST'])
def bad(bad_id='my_bad_id'):
    # url == /bad/?bad_id=my_bad_id
    url = flask.url_for('bad', bad_id=bad_id)
    print(url)
    return url


if __name__ == '__main__':
    app.run()
```

and the fix:

```python
@app.route('/bad/')
@app.route('/bad/<bad_id>', methods=['POST'])
def bad(bad_id='my_bad_id'):
    # url == /bad/?bad_id=my_bad_id
    url = flask.url_for('bad', bad_id=bad_id, _method='POST')
    print(url)
    return url
```
