### ISSUE TITLE
Option to change blueprints' templates precedence

### ISSUE THREAD

**Issue by wonkydonky** [pallets/flask#2664] opened 2018-03-19 08:49 UTC
When I create a new blueprint, the template_folder is added to a Flask defined path, and the precedence to locate a template is

1. `app/templates/` first
2. `app/my-blueprint/templates/` second

I understand this makes sense from the point of view of a developer who's trying to reuse the same blueprints on many different projects. He can plug in an existing blueprint and replace the templates from the main app if needed.
There is a different  use case however, where this behavior is unwanted and problematic. That is, when I'm structuring my applications into independent "modules" such that different teams can work independently on their own model/blueprint. The biggest problems is, that blueprints hits templates outside their domain, that is templates defied somewhere else in another blueprint folder. With large projects, this becomes a pretty difficult model to reason on and debug, and the blueprints are too much coupled to one another. Secondly, in this development context I would prefer a blueprint to have precedence over the base templates.
Ideally, I think Flask should have an option to change the precedence of templates. For example use the current behavior by default, but introduce a new config option "blueprints_templates_first=True/False" to be defined somewhere (either at the app level, or for every single blueprint). The expected behavior would be the opposite of the default behavior:

1. look in `app/my-blueprint/templates/` first
2. look in `app/templates/` second
3. **do  not** look into other blueprints folders

I've seen other people come up with the same issue over the years, and I don't understand why there is so much resistance against supporting this feature. There is a real use case for this. I've always appreciated Flask because it's minimalist, concise, powerful, and doesn't get in the way I choose to structure my project. Opposing this option just seems to me as going against the nature of Flask itself, because the framework is dictating to me how I have to structure my files on disk, something that only bigger frameworks do and that Flask has proudly never done. Every workaround to this, such as adding a new inner folder `my-blueprint/templates/my-blueprint/`, just feels like a hack that goes against the ideas of simplicity and clarity.

I, and I believe a lot of other Flask users as well, would really appreciate if you guys could add this configuration option to Flask. Thanks.

**Comment by davidism** [comment] 2018-03-19 13:15
Duplicate of: #1362. See also #376, #1537, #1815, #1843, #1963, and others.

This suggestion has been made before https://github.com/pallets/flask/issues/1361#issuecomment-220823219 and was responded to in the next comment. The same reasons still apply.

As explained in https://github.com/pallets/flask/issues/1361#issuecomment-220853048, a separate `render_template` can be written in a project if the dev doesn't want to type the blueprint name, but that doesn't carry over to `extends`, `import`, and `include`. You can also override `Blueprint.jinja_loader` to omit the directory entriely, but I don't know how this will interact with other behavior. The entire template system is overridable, there are multiple hooks at the app and blueprint level.

We are not going to change this.

**Closed by davidism** 2018-03-19 13:15 UTC

**Comment by ThiefMaster** [comment] 2018-03-19 13:17
The best option for you is to override `create_global_jinja_loader` in a custom `Flask` subclass, and return a custom `DispatchingJinjaLoader` subclass that does what you need. For example, overriding `_iter_loaders` and changing the order of the loaders might be enough.
