### ISSUE TITLE
Flask run gives misleading error message on actual import error

### ISSUE THREAD

**Issue by gnebehay** [pallets/flask#2625] opened 2018-02-08 21:19 UTC
### Expected Behavior

Using `flask run` should result in appropriate import error messages if erroneous imports are used in a flask app.

Consider the two flask apps `worksjustfine.py`:
```python
from flask import Flask
app = Flask(__name__)
```
and `completelymisleading.py`:
```python
import flask
import batrachomyomachy
app = flask.Flask(__name__)
```
If you fire up `worksjustfine.py`, it works just fine:
```bash
$ FLASK_APP=worksjustfine.py flask run
 * Serving Flask app "worksjustfine"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
If you fire up `completelymisleading.py`, you would expect something like this:
```bash
$ FLASK_APP=completelymisleading.py flask run
...
ImportError: No module named 'batrachomyomachy'
```
### Actual Behavior

```bash
$ FLASK_APP=completelymisleading.py flask run
Usage: flask run [OPTIONS]

Error: The file/path provided (completelymisleading) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py
```

This error message is completely misleading, because the file does exist and `flask run` also starts to import this file. I imagine that somewhere in the `flask run` code there is a `try ... except ImportError` that is meant for the situation when the actual flask app can not be found, but one would definitely need a more specific error message for other import errors.

### Environment

* Python version: 3.5.3
* Flask version: 0.12

**Comment by davidism** [comment] 2018-02-08 21:26
Duplicate of #2625. This has been fixed in master.

**Closed by davidism** 2018-02-08 21:26 UTC

**Comment by gnebehay** [comment] 2018-02-08 21:50
Ok, great! Could you just point me to the actual duplicate? #2625 seems to be this issue.

**Comment by davidism** [comment] 2018-02-08 22:06
#2214
