### ISSUE TITLE
Is it a bug ? 

### ISSUE THREAD

**Issue by milkeasd** [pallets/flask#4541] opened 2022-04-15 10:27 UTC
My python flask :

```
@app.route('/insert/item', methods=['POST'])
def insert_item():

    return ""
```

In html I try to post a request to /insert/item :

```
fetch('/insert/item', {
            method: 'POST', 
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({"item":"ABCD"}),
        })
```

My flask only response to the fetch the first time. 
It wont response afterward.

I have to add request_json = request.get_json() in the flask app to solve the issue

**Comment by davidism** [comment] 2022-04-15 13:17
Duplicate of https://github.com/pallets/flask/issues/4507, https://github.com/pallets/werkzeug/issues/2380, etc.

**Closed by davidism** 2022-04-15 13:17 UTC

**Comment by davidism** [comment] 2022-04-28 17:00
This will addressed by https://github.com/pallets/werkzeug/issues/2397, but reconsider why you're making a post request with data then not reading that data. Also note that the development server is not intended for production. Any production WSGI server handles this correctly already.
