### ISSUE TITLE
Docs - Testing Flask Applications

### ISSUE THREAD

**Issue by muratcankaracabey** [pallets/flask#3959] opened 2021-04-12 17:12 UTC
Environment:

- Python version:
- Flask version:1.1.x

In the documentation on page https://flask.palletsprojects.com/en/1.1.x/testing/ in part Testing Flask Applications, it says _We begin by adding a tests directory under the application root. Then create a Python file to store our tests (test_flaskr.py). When we format the filename like test_*.py, it will be auto-discoverable by pytest._ First of all, there is not such a file  _test_flaskr.py_ in the repository that the documentation points to. 

One other thing, in the code snippet from the same page:

```
import os
import tempfile

import pytest

from flaskr import create_app

@pytest.fixture
def client():
    db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
    flaskr.app.config['TESTING'] = True

    with flaskr.app.test_client() as client:
        with flaskr.app.app_context():
            flaskr.init_db()
        yield client

    os.close(db_fd)
    os.unlink(flaskr.app.config['DATABASE'])
```

The `create_app` import is not used. And `flaskr` module does not have a variable called `app` as it is being created as an app factory pattern. 

These mistakes make it hard to understand the documentation.

**Comment by davidism** [comment] 2021-04-12 17:21
Duplicate of https://github.com/pallets/flask/issues/3545

**Closed by davidism** 2021-04-12 17:21 UTC
