### ISSUE TITLE
python -m flask run raises RuntimeWarning

### ISSUE THREAD

**Issue by ybakos** [pallets/flask#2357] opened 2017-06-04 16:20 UTC
### Expected Behavior

Given a project with the following structure:

```
project/
    my_cool_app/
        __init__.py
```

```python
from flask import Flask

app = Flask(__name__)
```

Running the following should work without warnings:

```
FLASK_DEBUG=1 FLASK_APP=my_cool_app python -m flask run
```

I use `python -m flask run` in order to not need `my_cool_app/__init__.py` as `FLASK_APP`, per the discussion around [this issue](https://github.com/pallets/flask/issues/1847).

### Actual Behavior

A warning is printed on the console when using the reloader:

```
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125:
RuntimeWarning: 'flask.cli' found in sys.modules after import of package 'flask',
but prior to execution of 'flask.cli'; this may result in unpredictable behaviour
```

### Environment

* Python version: 3.6.1 (MacOS 10.12.5)
* Flask version: 0.12.2
* Werkzeug version: 0.12.2

**Comment by wgwz** [comment] 2017-06-04 16:54
Are you using a virtualenv? If not, give it a try and see if you still get the same error.

**Comment by davidism** [comment] 2017-06-04 17:03
I can't reproduce this on 0.12 or master. I don't have a Mac though. `runpy.py` will indeed raise this warning, but I just can't trigger it.

**Comment by davidism** [comment] 2017-06-04 17:06
Also, installing your app as a package allows you to use `FLASK_APP=my_cool_app flask run`, which is the preferred method.

**Comment by ybakos** [comment] 2017-06-04 18:19
@wgwz I am indeed using virtualenv.
@davidism Ok, but forgive my ignorance here: doesn't installing my app as a package pollute my requirements.txt?

**Comment by davidism** [comment] 2017-06-04 18:20
Don't put in in your requirements file, that file describes the dependencies of your app. Your app is not a dependency of itself.

**Comment by ybakos** [comment] 2017-06-04 18:21
But if I install it as a package, when I `pip freeze > requirements.txt` my application would be in the list.

**Comment by ybakos** [comment] 2017-06-04 18:21
FWIW, the warning is printed after `Restarting with stat`.

**Comment by ybakos** [comment] 2017-06-04 18:23
And the specific flask app has a repo here: https://github.com/osu-cascades/iot-lab-inventory

**Comment by davidism** [comment] 2017-06-04 18:25
Then remove it if you insist on using `pip freeze` to populate your requirements. For what it's worth, I'm against `requirements.txt`, but that's a style thing.

**Comment by davidism** [comment] 2017-06-04 18:28
Installing your project in develop mode is good practice. The fact that `pip freeze` doesn't understand it is a problem with pip, although I don't know how they'd be able to avoid it, since they can't know which editable package is the current project.

**Comment by ybakos** [comment] 2017-06-04 18:30
BTW, I don't get any kind of warning when `FLASK_APP=my_cool_app/\_\_init\_\_.py` and I run with `flask run`.

**Comment by davidism** [comment] 2017-06-04 18:33
Yes, because `python -m` does weird stuff and it's hard to write the reloader to support that. I recommend using the `flask` command whether you choose to install as a package or not. given that this is just a warning and the app is still clearly working, I'm inclined to close this.

**Comment by ybakos** [comment] 2017-06-04 18:59
Thanks @davidism (and thanks for all things Flask), feel free to close. As long as the warned "unpredictable behavior" isn't really a concern, I'll live with the verbose output.

**Comment by davidism** [comment] 2017-06-04 19:17
I think we can actually get rid of the warning, it looks like `flask.cli.main` can be smarter about choosing the name. It all comes from trying to support 2.6. 😢

**Comment by ybakos** [comment] 2017-06-04 19:37
Glad this wasn't a total distraction. 😄

**Closed** 2017-06-04 19:38 UTC
Labels: cli
