### ISSUE TITLE
Multi-level error handling support broken in ver: 1.1.0

### ISSUE THREAD

**Issue by ArshanKhanifar** [pallets/flask#3287] opened 2019-07-06 00:23 UTC
---

### Expected Behavior
Catching an exception type in an error handler and raising another exception type breaks the flask app instead of passing control to the corresponding error handler.

Given the following `flask` application:
```
from flask import Flask, jsonify
from werkzeug.exceptions import BadRequest, HTTPException

class CustomAppException(Exception):
    pass

class AppFactory(object):
    def create(self):
        app = Flask(__name__)

        @app.errorhandler(HTTPException)
        def handle_generic_http_exceptions(e):
            return jsonify({
                "error": str(e)
            }), e.code

        @app.errorhandler(CustomAppException)
        def unhandled_meteor_errors(e):
            raise BadRequest(str(e))

        @app.route("/")
        def raise_error_endpoint():
            msg = 'some bad msg'
            raise CustomAppException(msg)

        return app
```
A get request to the endpoint `/` should show the following response: 
```
{
"error": "400 Bad Request: some bad msg"
}
```

### Actual Behavior

Instead it gives this response: 
```
{
"error": "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
}
```

### Environment
* Python version: 3.7.3
* Flask version: 1.1.0
* Werkzeug version: 0.15.4

```
$ pip freeze
atomicwrites==1.3.0
attrs==19.1.0
certifi==2019.6.16
Click==7.0
Flask==1.1.0
importlib-metadata==0.18
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
more-itertools==7.1.0
packaging==19.0
pluggy==0.12.0
py==1.8.0
pyparsing==2.4.0
pytest==5.0.1
six==1.12.0
wcwidth==0.1.7
Werkzeug==0.15.4
zipp==0.5.1
```

This is not broken in `Flask 1.0.3`.  Here's the [repo](https://github.com/ArshanKhanifar/flask_bug_demonstration.git) that tests this.

**Comment by davidism** [comment] 2019-07-06 00:29
I'll look into it, but this specific case can be fixed by returning from the error handler instead of raising.

**Comment by davidism** [comment] 2019-07-06 00:36
This is expected behavior now. From the changelog:

> Error handlers for `InternalServerError` or `500` will always be passed an instance of `InternalServerError`. If they are invoked due to an unhandled exception, that original exception is now available as `e.original_exception` rather than being passed directly to the handler. The same is true if the handler is for the base `HTTPException`. This makes error handler behavior more consistent. #3266

That your code worked before is sort of an accident, "multilevel handling" was not intended and in fact was only "two level". Error handlers should `return` a valid response, further errors are handled at a higher "failsafe" level.

**Closed by davidism** 2019-07-06 00:36 UTC

**Comment by ArshanKhanifar** [comment] 2019-07-06 00:52
Thanks, I was treating them like normal python exceptions and had this kind of `catch-and-reraise` all over my code. Yikes 😬
