### ISSUE TITLE
large file uploads eating up memory

### ISSUE THREAD

**Issue by cecemel** [pallets/flask#2086] opened 2016-11-16 16:35 UTC
Hi, 

when handling large file uploads +300MB, the files seem to be cached in memory till the upload is finished. This is not very practical.
The [doc](http://flask.pocoo.org/docs/0.11/patterns/fileuploads) states: 

>(...) So how exactly does Flask handle uploads? Well it will store them in the webserver’s memory if the files are reasonable small otherwise in a temporary location

I am unsure on how to interpret this, but as I saw it: cache the data on disk till the file is uploaded, before moving on. :-)

So my question is: is storing everything in memory during upload, intended behaviour?

To give a little more details on the code: 

```
def store_upload(project_id):
    file = request.files['file']
    # boiler plate checks ...
    file.save(os.path.join(destination_base, destination))  #save file to decent location
    return _response_stuff()
```
I am using python 3.5, flask 0.11.1. 

PS: I went through #pocoo and github issues here, but couldn't find any answer matching my request

Thanks!

**Comment by cecemel** [comment] 2016-11-17 09:33
Looks similar to a werkzeug issue. (which is closed) 
[here](https://github.com/pallets/werkzeug/issues/510)

The werkzeug version I am using: 0.11.10, so the fix should be applied.

Here someone is experiencing the same issue as I am. [here](https://github.com/codalab/codalab-cli/issues/301)

Shall I have a look there?

**Comment by lnielsen** [comment] 2016-11-21 15:04
There's two issues you are likely experiencing:
- Werkzeug's multipart form parser is very slow for large files - see pallets/werkzeug#875
- Werkzeug will write a temporary file for anything larger than 500KB: https://github.com/pallets/werkzeug/blob/master/werkzeug/formparser.py#L41

If you want to upload large files through Flask I suggest you simply stream them directly in the request body. It's magnitudes faster on both client and server side as there's no encoding/decoding of the file. Basically you just read from ``request.stream``.

This is what we've done on zenodo.org and we're having users upload 200GB+ datasets over HTTP with speeds that's only limited by our storage clusters incoming capacity.

**Comment by cecemel** [comment] 2016-11-22 16:09
Thanks for your tip!
 However, reading from the stream, does not seem to fix the issue... The memory consumption still grows with the same order as the size of the file it receives...
The code is basically doing: 
```
#(...)
 with open(temp_file, 'wb') as f:
        while not request.stream.is_exhausted:
            f.write(request.stream.read(10))
```
Also using request.stream.read() does not seem to make any difference.
Perhaps I am doing something wrong.

All tips (even to better frame the problem) are welcome. 
thanks again

**Comment by lnielsen** [comment] 2016-11-22 19:18
Check e.g. the request.mimetype and make sure it is not ``application/multipart-formdata`` (if it is, the form parser will likely kick in no matter what).

A side not is that likely you want to read bigger chunks that 10 bytes when writing the file.

**Comment by cecemel** [comment] 2016-11-23 16:30
Hi, 

thanks for the tips again! 
Yes the 10 bytes reading was just illustrative to make sure the chunks remain small. 

However, I am Still facing the same issue, even with other mimetypes. With or without WSGI server (gunicorn). Memory usage just explodes.

But it looks like more and more an issue with werkzeug. Citing someone in [this issue](https://github.com/codalab/codalab-cli/issues/301)

>(...) What it does instead is always store the entire file in memory, at least in one part of the code.

I will try to look for alternatives and bump the werkzeug people
Thanks for all the help!

**Comment by cecemel** [comment] 2016-11-24 10:08
To better frame the issue, I created a docker image which may be tried out.

To run it:

`docker run --name flask_upload_issue -p 5000:5000 docker.io/cecemel/flask_upload_issue`

Client side you could upload a file, like

`curl -X POST -F file=@some_large_file http://localhost:5000/uploads`

To monitor memory usage

`docker stats flask_upload_issue`

To check the code, go inside the container (so it should be running):

`docker exec -ti flask_upload_issue bash`

The folder 'example' contains the code.

Perhaps this gives more clues.
Thanks!

**Comment by ivarref** [comment] 2016-11-25 13:11
Cross post from https://github.com/pallets/werkzeug/issues/1041 :

Here is a sample Flask application for handling huge file uploads:
https://gitlab.nsd.uib.no/ire/python-webserver-file-submission-poc/blob/master/flask_app.py

At my machine it handles a 22 GiB file in ~60 seconds. Memory usage is constant at about 13 MiB.

**Comment by davidism** [comment] 2017-06-02 15:00
Closing, this is a Werkzeug issue and is already reported there.

**Closed by davidism** 2017-06-02 15:00 UTC

**Comment by bingtel** [comment] 2017-06-15 09:06
@ivarref I tried your way， but **buf /cache** will be used too much：

You can reproduce the result with 'free -m'

**Comment by nejdetckenobi** [comment] 2018-01-19 09:21
It is worth to note that after @ivarref's approach, config keys like `MAX_CONTENT_LENGTH` can not be used automatically (because of bypassing Flask I think). I'll examine further and share the results.

**Comment by dhruvp** [comment] 2018-02-11 00:38
@ivarref thank you for the snippet! It works great locally but when I put it in an environment w/ Gunicorn behind an NGINX server, I keep seeing ClientDisconnect errors during the parsing of the from. Any idea what might be going on? Have you encountered this?

**Comment by ivarref** [comment] 2018-02-13 12:06
Sorry @dhruvp I have no suggestion.

**Comment by mhocine** [comment] 2019-01-06 14:49
Thank you ! This Helped me !

**Comment by OdysLam** [comment] 2019-08-23 12:34
Hey @ivarref ,

Thank you for your snippet! What kind of request must be done to that flask server? I hope that my question is not extremely elementary.

Cheers! :)

**Comment by ivarref** [comment] 2019-08-24 11:04
Hey @OdysLam 

Here is an example request using curl:

```bash
curl -XPOST -F "file=@./my.big.file.bin" "http://localhost:8090/"
```

This is documented at the [repository root](https://gitlab.nsd.no/ire/python-webserver-file-submission-poc).

Warning: Please note that this code uses Flask version 0.11.1, while as of writing this Flask 1.1.1 has been released. Also I have not looked at this code since writing it.

**Comment by binyu-bingo** [comment] 2019-12-17 11:33
> There's two issues you are likely experiencing:
> 
> * Werkzeug's multipart form parser is very slow for large files - see [pallets/werkzeug#875](https://github.com/pallets/werkzeug/issues/875)
> * Werkzeug will write a temporary file for anything larger than 500KB: https://github.com/pallets/werkzeug/blob/master/werkzeug/formparser.py#L41
> 
> If you want to upload large files through Flask I suggest you simply stream them directly in the request body. It's magnitudes faster on both client and server side as there's no encoding/decoding of the file. Basically you just read from `request.stream`.
> 
> This is what we've done on zenodo.org and we're having users upload 200GB+ datasets over HTTP with speeds that's only limited by our storage clusters incoming capacity.

Hi @lnielsen 

How you deal with the request.stream?
request.stream.read() doesn't work for me. It still consums lots of memories.
