### ISSUE TITLE
Add a file mode parameter to flask.Config.from_file()

### ISSUE THREAD

**Issue by ejwick** [pallets/flask#4989] opened 2023-02-18 15:23 UTC
Python 3.11 introduced native TOML support with the `tomllib` package. This could work nicely with the `flask.Config.from_file()` method as an easy way to load TOML config files:

```python
app.config.from_file("config.toml", tomllib.load)
```

However, `tomllib.load()` takes an object readable in binary mode, while `flask.Config.from_file()` opens a file in text mode, resulting in this error:

```
TypeError: File must be opened in binary mode, e.g. use `open('foo.toml', 'rb')`
```

We can get around this with a more verbose expression, like loading from a file opened with the built-in `open()` function and passing the `dict` to `app.Config.from_mapping()`:

```python
# We have to repeat the path joining that from_file() does
with open(os.path.join(app.config.root_path, "config.toml"), "rb") as file:
    app.config.from_mapping(tomllib.load(file))
```

But adding a file mode parameter to `flask.Config.from_file()` would enable the use of a simpler expression. E.g.:

```python
app.config.from_file("config.toml", tomllib.load, mode="b")
```

**Comment by davidism** [comment] 2023-02-18 15:33
You can also use:

```python
app.config.from_file("config.toml", lambda f: tomllib.load(f.buffer))
```

**Comment by ejwick** [comment] 2023-02-18 16:10
Thanks - I was looking for another way to do it. I'm happy with that for now, although it's worth noting this about `io.TextIOBase.buffer` from the docs:

> This is not part of the [TextIOBase](https://docs.python.org/3/library/io.html#io.TextIOBase) API and may not exist in some implementations.

**Comment by davidism** [comment] 2023-02-18 16:14
Oh, didn't mean for you to close this. I think a `text=True` parameter would be better, easier to use `True` or `False` rather than mode strings.

**Comment by DeepakSingh260** [comment] 2023-02-22 07:32
can i work on this?

**Comment by davidism** [comment] 2023-02-22 13:24
No need to ask to work on an issue. As long as the issue is not assigned to anyone and doesn't have have a linked open PR (both can be seen in the sidebar), anyone is welcome to work on any issue.

**Closed** 2023-02-23 19:13 UTC
