### ISSUE TITLE
running flask with debug mode throws an error

### ISSUE THREAD

**Issue by timbicker** [pallets/flask#2485] opened 2017-10-08 12:10 UTC
### Expected Behavior

If I active debug mode the program fails as is shown below. However with deactivated debug mode the program runs fine.

```python
from flask import Flask

app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    app.run()
```

### Actual Behavior

```pytb
* Serving Flask app "flask_hello_world"
 * Forcing debug mode on
 * Restarting with stat
  File "C:\Users\Tim\Anaconda3\envs\flaskr\Scripts\flask.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Users\Tim\Anaconda3\envs\flaskr\Scripts\flask.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

### Environment

I am running it on Windows 10. Python and packages are installed through Anaconda.

* Python version: 3.6
* Flask version: 0.12.2
* Werkzeug version: 12.2

**Comment by RonnyPfannschmidt** [comment] 2017-10-08 20:26
at first glance this looks like whatever you use tries to execute the flask windows exe file as python script, which cannot work ever

**Comment by davidism** [comment] 2017-10-08 20:34
duplicate of pallets/werkzeug#1136

**Closed by davidism** 2017-10-08 20:34 UTC
