### ISSUE TITLE
`create_app` is not used in testing docs

### ISSUE THREAD

**Issue by YahyaFazlani** [pallets/flask#4137] opened 2021-06-06 07:13 UTC
I was viewing the [testing docs](https://flask.palletsprojects.com/en/2.0.x/testing/) and found that the `create_app` function imported for the fixture is not used. Also `flaskr` is not imported directly, only the `create_app` function is. I don't think this is how it should be or am I missing something?

**Comment by davidism** [comment] 2021-06-06 16:21
Duplicate of #3545

**Closed by davidism** 2021-06-06 16:21 UTC
