### ISSUE TITLE
Issue with sending large-ish CSV files to Flask

### ISSUE THREAD

**Issue by mdemin914** [pallets/flask#2617] opened 2018-02-01 02:49 UTC
I am trying to send a csv file as a base64 encoded string in the body of a post request to a flask server. It works find for small files. But when I try to post a file above ~150k the server does not respond and there is no error message. It seems to get hung up on `body = request.get_json()`. This non-responsiveness happens through postman and node. To throw a wrench into the problem, I can submit the file fine using pythons requests library. I am not sure what is causing this or what the difference between the three requests. The headers all look really similar and are included in the repo. I have included the minimal server (server.py), working python request (test.py), the not working node request (jstest.js) and the not working postman collection. Thanks for any help.

Here is a simple reproduction MCVE https://github.com/mdemin914/flask-largeish-csv-file-error-reproduction

### Environment

* Python version: 2.7.13
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment] 2018-02-01 03:50
Duplicate of pallets/werkzeug#875

**Closed by davidism** 2018-02-01 03:50 UTC

**Comment by mdemin914** [comment] 2018-02-01 07:56
Could you please clarify how this this related? I am sending a json request with a large string and not a multipart/form-data. I had issues with sending large files with multipart/form-data, which is why i switched to a json payload. Sorry if I missed something @davidism

**Comment by lambdaq** [comment] 2018-02-01 07:58
150k is not "large", I guess it's not related to issue #875 

get_json() might be the culprit. Try profiling more.

**Comment by mdemin914** [comment] 2018-02-01 18:58
@lambdaq running the profiler it seems that posix.waitpid is what is taking up all the time. I am new to python and am not quite sure how to debug further.
