### ISSUE TITLE
Importing from PWD using `python -m` fails in development environment

### ISSUE THREAD

**Issue by jwg4** [pallets/flask#2817] opened 2018-06-06 11:16 UTC
### Expected Behavior

We have a Flask app defined in a file which sits inside a folder, say `app/run.py`:

```python
from flask import Flask

from foo import bar

app = Flask(__name__)

app.run()
```

The file imports from the top-level directory, in this case `foo.py`

```python
bar = "SOMETHING TO IMPORT"
```

The empty file `__init__.py` exists in the directory `app`.

Using the default environment (production), we can run the Flask app by invoking the module from the top-level directory, using `-m`

```
python -m app.run
```

The `foo` module is imported correctly and the app runs.

```
 * Serving Flask app "run" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

### Actual Behavior

If we try to use the development environment, setting the `FLASK_ENV` variable, it fails.

```
FLASK_ENV=development python -m app.run
```

```pytb
 * Serving Flask app "run" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/home/jack/z/flask_dev/app/run.py", line 3, in <module>
    from foo import bar
ImportError: No module named foo
```

### Environment

* Python version: 
    Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
    [GCC 5.4.0 20160609] on linux2

* package versions:
    click==6.7
    Flask==1.0.2
    itsdangerous==0.24
    Jinja2==2.10
    MarkupSafe==1.0
    Werkzeug==0.14.1

**Comment by lepture** [comment] 2018-06-07 07:15
Close it since it is not a bug of Flask.

It seems a misunderstanding of Python PATH. I don't know where you put your `foo.py` according to your description. It is better to ask your question on StackOverflow with a minimal example.

**Comment by lepture** [comment] 2018-06-07 08:42
> The file imports from the top-level directory, in this case foo.py

I'm sorry, but I don't fully understand your `top-level`. Is it `/home/jack/z/flask_dev/app/foo.py` or `/home/jack/z/flask_dev/foo.py`? I can only guess.

**Comment by lepture** [comment] 2018-06-07 08:47
It is a werkzeug reloader issue.

**Comment by lepture** [comment] 2018-06-07 08:48
Maybe related to https://github.com/pallets/werkzeug/issues/461

**Comment by jwg4** [comment] 2018-06-07 09:48
Thanks! Trying to understand exactly what that issue and #1246 imply for this.

**Closed** 2018-06-07 11:09 UTC
