### ISSUE TITLE
Flask==1.1.x no longer calls force_type on user-defined types

### ISSUE THREAD

**Issue by tsx** [pallets/flask#3591] opened 2020-04-29 13:54 UTC
I override `Response.force_type` to handle my own custom responses (and some extra builtin types like lists). I recently tried to upgrade to Flask==1.1.x but it no longer calls my handler and throws an exception instead.

### Reproduce
```python
import pytest
from flask import Flask, Response, jsonify


class MyCustomType:
    def to_json(self):
        return {'ok': 1}


class MyResponse(Response):
    @classmethod
    def force_type(cls, response, environ=None):
        if isinstance(response, list):
            return jsonify(response)
        if isinstance(response, MyCustomType):
            return jsonify(response.to_json())
        return super(MyResponse, cls).force_type(response, environ=environ)


class MyApp(Flask):
    response_class = MyResponse


my_app = MyApp(__name__)


@my_app.route('/list')
def get_list():
    return ['my_element']


@my_app.route('/my')
def get_my():
    return MyCustomType()


@pytest.fixture
def client():
    with my_app.test_client() as client:
        yield client


def test_force_type_list(client):
    assert client.get('/list').json == ['my_element']


def test_force_type_my(client):
    assert client.get('/my').json == {'ok': 1}

```

### Exception

```pytb
Traceback (most recent call last):
  File "/home/closeio/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/closeio/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/closeio/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/closeio/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a MyCustomType.
```

### Environment

* Python version: 3.6.9
* Flask version: 1.1.4 (it works on 1.0.4)
* Werkzeug version: 0.15.6

### PR that caused the issue

https://github.com/pallets/flask/pull/3235

**Comment by davidism** [comment] 2020-04-29 15:36
Duplicate of #3291

**Closed by davidism** 2020-04-29 15:36 UTC
