### ISSUE TITLE
Disable static file caching with SEND_FILE_MAX_AGE_DEFAULT = 0 when FLASK_ENV is set to development

### ISSUE THREAD

**Issue by nickjj** [pallets/flask#3936] opened 2021-03-15 14:11 UTC
In most other web frameworks static file caching would be disabled when the app is running in development mode. Since `FLASK_ENV` is something we have available to then maybe we can set `SEND_FILE_MAX_AGE_DEFAULT = 0` when we're in development mode. If `FLASK_ENV` isn't the correct variable to hook into maybe it could be set when `DEBUG` is set to true instead.

I've seen this question pop up on IRC about 50 times in the last few years where someone wonders why after changing their CSS or JS in development they don't see the changes in their browser. The "fix" is to do a hard reload in your browser (CTRL+F5 on Windows / Linux) which forces browsers to serve an un-cached copy of the file.

I know in my Flask course, this question has come up dozens of times as well until I mentioned setting this config value to 0.

I can't think of a use case where you would want static file caching enabled in development and if you did you could always explicitly set the max age to whatever value you want. 

What do you think?

**Comment by davidism** [comment] 2021-03-15 14:53
Duplicate of https://github.com/pallets/werkzeug/pull/1886

**Closed by davidism** 2021-03-15 14:53 UTC
