### ISSUE TITLE
Flask crashes on startup

### ISSUE THREAD

**Issue by ignaloidas** [pallets/flask#2479] opened 2017-09-30 08:12 UTC
---

### Expected Behavior

The app should've run

```python
any flask app really
```

### Actual Behavior

Flask didn't startup properly and threw an errorcode

```pytb
$ flask run
* Serving Flask app "falsker"
* Forcing debug mode on
* Restarting with stat
File "C:\Anaconda3\envs\flaskui\Scripts\flask.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Anaconda3\envs\flaskui\Scripts\flask.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

### Environment

* Python version: 3.6.2 on Anaconda
* Flask version:0.12.2
* Werkzeug version:0.12.2

**Comment by davidism** [comment] 2017-09-30 09:17
Duplicate of pallets/werkzeug#1136, pallets/werkzeug#1138

**Closed by davidism** 2017-09-30 09:17 UTC

**Comment by ignaloidas** [comment] 2017-09-30 09:51
any way to make a temp fix while it's being worked on?

**Comment by davidism** [comment] 2017-09-30 10:27
https://github.com/pallets/werkzeug/issues/1136#issuecomment-316487106
