### ISSUE TITLE
What is the release schedule for 1.0?

### ISSUE THREAD

**Issue by lipis** [pallets/flask#1575] opened 2015-09-28 17:54 UTC
What are the plans for the 1.0 release.  This was brought up last year and there hasn't been any announcements since then.  What progress is being made and what still remains?

**Comment by davidism** [comment] 2015-09-28 18:54
https://github.com/mitsuhiko/flask/milestones/1.0

There's a great place to start contributing if you want to see a new release sooner.

**Comment by stephane** [comment] 2015-10-05 23:33
There are many trivial Pull Requests such as https://github.com/mitsuhiko/flask/issues/1546 but nobody to close or merge them. Except a few commits from @untitaker, @rduplain, all the others come from @mitsuhiko. The mailing list is very quiet too.

It would be great if a core dev team could be created to support this project.
May be someone has more information about the workflow and can explain why the coding pace is so slow these days?

**Comment by davidism** [comment] 2015-10-06 01:17
Not that this is a justification for whatever pace the maintainers decide to take, but it might be that Flask is working well for what it was designed to do.  This is anecdotal, but I've been running a Flask project for three years straight now, and no issue in that project has been because of Flask.  The community is obviously still active, and issues are discussed and problems solved.

A (quick) glance at [pull requests created after the 0.10.1 release][1] (total 206) shows that they fall into a few categories.

* Corrections to documentation or examples (often minor) (this is the *vast* majority of the prs, there are whole pages where "typo/docs/example" are in every title)
* Enhancements for convenience (often minor)
* Truly new or different behavior (feature, deprecation, etc.) (I estimate 5)

Getting a quick idea of other issues is more difficult, since they are just closed, there's nothing to merge to show that something was actually done.  From my experience following the tracker for a few years, the majority of them are support questions, denied reports, or request that turned into prs (many dealing with docs in some way).

Again, I cannot read the minds of the maintainers, but it seems entirely plausible to me that they don't feel that there is enough major content to make a release that they will have to officially support.  See mitsuhiko's [thoughts on this][2] (published soon after the 0.10.1 release).

> The things I wrote over the last few years all work so well for *me*, that I don't need to fix problems or add things.

Perhaps if people could point to specific bugs or enhancements that are vital to them using Flask, those issues could be added to the milestone to give it more weight.  Just saying "I want a new release" isn't as effective without saying *why*.  It would be great to see more statistics about what a new officially supported release would gain everyone.

[1]: https://github.com/mitsuhiko/flask/pulls?q=updated%3A%3E2013-06-14+is%3Apr+is%3Amerged
[2]: http://lucumr.pocoo.org/2013/11/28/emotional-programming/

**Comment by davidism** [comment] 2015-10-06 01:32
A side note, I find the title of this issue very unfortunate.  It's incredibly aggressive and offers nothing constructive.  The discussion it can lead to can be constructive, but it should really be worded more reasonably.

**Comment by lipis** [comment] 2015-10-06 07:59
@davidism You are right about the aggression and maybe I shouldn't.. I also agree that I don't have any major issues with the current version.. but there are fixes here and there and a year ago that was written.. https://github.com/mitsuhiko/flask/issues/1140#issuecomment-53157622 so in short I just wanted to check what is going on..

**Comment by davidism** [comment] 2015-10-06 15:17
It's also important to note that many significant changes are in Werkzeug or Jinja, both of which have seen a release much more recently than Flask.

**Comment by davidism** [comment] 2015-10-06 15:23
@lipis as the author, I'm pretty sure you can change the title of this issue, it you decide you should.

**Comment by lipis** [comment] 2015-10-06 15:25
@davidism I just changed it.. :)

**Comment by stephane** [comment] 2015-10-06 19:53
You're right @davidism, many significant changes are in other components and Flask is stable. However, the previous release 0.10.1 is two years old and until the next release, the 761 commits in master won't be very useful.

I really like to see a release of Flask to use the new CLI feature. Last year (around august 2014), click 2.0 support has been merged so I started to use Flask master in the hope of a imminent release but now, one year later, I rewrote my CLI commands with argparse to not depend of an unreleased version anymore (I don't want to publish my own Flask package on a private pypi). Frequent releases (even minors) give me more confidence in the project.

**Comment by lipis** [comment] 2015-10-06 20:23
@stephane :100:

**Comment by klinkin** [comment] 2015-10-06 22:08
+100500

**Comment by davidism** [comment] 2015-10-06 22:55
Just to head this off before it gets started, +something comments aren't useful on their own, they just cause noise for everyone watching the tracker.  As I prompted, a good comment would be "+1 I agree, I'm waiting for <feature x that hasn't already been mentioned>."  Please try to further discussion, rather than dogpile.

@stephane Click was one of the features I could think of off the top of my head that was really new.  But I don't think it's essential to using Flask, and has already been [backported][1] to the stable release via an extension.  My point with the analysis was that despite there being a large number of commits/prs, my impression was that the vast majority of them are docs/examples/test/other cleanup.

I may be in the minority here, but I'm not really worried about frequent releases.  If there's a big, breaking issue, yes a fix should be issued.  But not seeing constant releases doesn't drain me of confidence in the project.  I'd judge the health of the project based on the entire picture of activity, not just releases.  By that measure, I think Flask is healthy.

[1]: https://pypi.python.org/pypi/Flask-CLI

**Comment by davidism** [comment] 2015-10-06 23:05
Hopefully I don't give the impression that I'm against more releases; I'm neither for nor against them.  It would be useful to see minor releases as minor changes roll in, rather than letting them build up for years.  However, my confidence in the project is not based just on releases, but on the whole ecosystem.

Click was a big feature I could think of off the top of my head.  It's not essential, but it's also been [backported via an extension][1].

[1]: https://pypi.python.org/pypi/Flask-CLI

**Comment by mitsuhiko** [comment] 2015-10-07 18:24
I have been trying to actually push myself to do a release the last two weeks but the main reason is that it's not just Flask that needs a new release, there is a whole chunk of work left in actually redoing the website and everything that goes with it.  I personally use both master and last release version on various different projects and as @davidism mentioned, there is nothing that is particularly on fire in Flask itself for the most part.

It's a very lean project compared to many other things as it mostly bolts things together.  I really want to push out a release very soon however, but I might change the version number from 1.0 away to something slightly less emotional.

The 1.0 release should at least go with an updated documentation and website and I currently do not have the time for that part (any volunteers? :D)

**Comment by Jaza** [comment] 2015-10-07 22:37
@mitsuhiko Personally I'm in favour of the next release being 1.0, and am looking forward to it. Doesn't have to be "The Big 1.0", doesn't have to imply sweeping changes / heated emotions / frantic bug-fixing. On the contrary, it could just be done to signify Flask's maturity, and to celebrate it being (a bit over) [5 years old](https://github.com/mitsuhiko/flask/issues/1423).

Perhaps similar to the [Linux kernel 3.0 release](https://lkml.org/lkml/2011/7/21/455), in which Linus said:

> As already mentioned several times, there are no special landmark
> features or incompatibilities related to the version number change,
> it's simply a way to drop an inconvenient numbering system in honor of
> twenty years of Linux.

Re: volunteers for updated documentation and website. Happy to help out. Can you point us to any todo lists or roadmaps for that?

**Comment by jwogrady** [comment] 2015-10-07 23:25
We are conditioned to believed software needs constant updates... Perhaps it's because of the strong gatekeeper keeping everyone off the update treadmill that attracts so many people to this project.

**Comment by lipis** [comment] 2015-10-07 23:38
I'm no saying that we need to make releases just to make them, but few patches here and there are always needed. Only if the software/library is useless doesn't need any update. Even if there are not major flows or issues with Flask (obviously) there are 761 new commits since the last _stable_ release. All we're asking to have more regular releases and close/discard issues if they are not relevant.

We are all aware of this open source madness.. noone is getting paid for it and we are all doing it on our spare time, but that's the side effect of having 16K :star:

**Comment by mitsuhiko** [comment] 2015-10-08 09:06
The main problem is that the website is not in a good state.  The snippets are largely unmaintained, the extension list is as well and it makes for a horrible experience, especially after the mailinglist moved.  I know a 1.0 release and an updated website does not have to happen at the same time, but it kinda is expected :)

**Comment by lipis** [comment] 2015-10-08 09:24
Totally understandable.. So lets speed up with the docs.. Unfortunately I suck in documentation and I also have my own outdated documentation to finish one day :) So I'll just have to wait patiently.. :walking: :watch:

**Comment by ThiefMaster** [comment] 2015-10-08 09:24
And nobody likes writing documentation ;)

**Comment by lipis** [comment] 2015-10-08 09:57
Here you are.. all of the 5 years in 2 minutes: https://www.youtube.com/watch?v=BIyzNDluHCY
<img width="559" alt="screen shot 2015-10-08 at 11 56 45" src="https://cloud.githubusercontent.com/assets/125676/10363238/afbe97c4-6db3-11e5-85fa-955d1dbcda77.png">

**Comment by justanr** [comment] 2015-10-08 11:22
@thiefmaster @mitshukio Is it docstrings or sphinx docs that need updating?

**Comment by mitsuhiko** [comment] 2015-10-08 11:58
It's mostly ensuring that the documentation is cohesive to some of the new changes in Flask 1.0.  The biggest one is to somehow make it clear why the `flask` executable is recommended over `app.run()` for local development and to gently guide this through from the documentation.

**Comment by robertlagrant** [comment] 2015-10-08 23:22
Some way for the snippets to stay up to date without needing mitsuhiko's time would be great; a (the?) Flask-Testing snippet had some issues, from what I remember.

I think the snippets are a brilliant idea, but perhaps a way to keep them up to date somehow - even perhaps with clever stuff such as automated tests written by the snippet author that can shout for attention automatically if broken on a new version - would be great.

**Comment by sasha0** [comment] 2015-10-10 09:40
> The main problem is that the website is not in a good state. The snippets are largely unmaintained, the extension list is as well and it makes for a horrible experience, especially after the mailinglist moved. I know a 1.0 release and an updated website does not have to happen at the same time, but it kinda is expected :)

@mitsuhiko what is the best way to proceed with this? Maybe you could create issues for the outstanding things regarding website so contributors can start to help with this?

**Comment by justanr** [comment] 2015-10-10 14:49
@mitsuhiko Is there any existing docs about why the `flask` command is better than `app.run`? This is the first I'm hearing about this (though, I'll admit to being out of the loop with the click integration), but I'm more than happy to draft up documentation about why it's an improvement.

**Comment by davidism** [comment] 2015-10-10 16:20
The `flask` command is a Click interface.  It includes `app.run`, as well as any other commands that were added to the app using `app.cli`.  It also means people are instructed to use a consistent way to start the app, rather than the multitude of different methods that cause sometimes obscure problems (especially `python -m`).

**Comment by mitsuhiko** [comment] 2015-10-10 18:55
@justanr conceptionally superior because it does not crash on syntax error, it does not ever give you connection reset and it will only execute your app once if the reloader is on.  Cannot be done with `app.run()`.

**Comment by cenouro** [comment] 2015-10-20 14:03
If the problem is documentation and the site, why not make a "release candidate release" with all these commits ahead of stable? That way the code can be frozen and documentation can be developed more consistently. Writing documentation is already a pain; writing documentation for a rolling release project will inevitably be avoided by everyone.

**Comment by davidism** [comment] 2015-10-20 16:15
I have discussed making release candidates with @mitsuhiko and he agreed with the idea.  He's the only one who can push to PyPI, but there are plans to do this eventually.

**Comment by lipis** [comment] 2015-10-20 16:25
:dancers:

**Comment by jwogrady** [comment] 2015-10-20 16:37
I'm interested in writing documentation. My question is how do you go about that if you didn't write the code. To get started I would need some direction, perhaps assigned tasks, but after that...

**Comment by cescoferraro** [comment] 2015-10-20 16:47
My 2 cents: Have you guys ever thought about coding a genius like kind of
documentation where anyone can add layers of information on top of a
barebone template and the most up voted/right one make it to the actual
docs? Cannot think of a more open source solution than that. It might be
useful for other #pocoo projects too.

**Comment by davidism** [comment] 2015-10-20 17:02
This is more the high-level conceptual/usage documentation, not the individual code docstrings.  Being familiar with how to use Flask is just as valuable as being familiar with the underlying code.  I have some vague ideas about what needs to be done, but I need to sit down this weekend to create specific issues.

@cescoferraro I'd rather keep the current system, where people who want to document can submit a pull request, have it reviewed, and a team member decides whether to merge it.  If you'd like to develop your idea out further it sounds like it could be interesting but it also sounds like a lot of overhead to maintain.

**Comment by cenouro** [comment] 2015-10-20 17:36
@jwogrady Even if you are not familiar with the code base, you can always write sample apps that exercising features. Another possibility is maybe checking non-trivial questions on StackOverflow and improving the docs if the user cannot infer the correct usage from the docs.

**Comment by cescoferraro** [comment] 2015-10-20 18:56
@DavidLord I might have misunderstood what you were proposing.

**Comment by cescoferraro** [comment] 2015-10-20 19:04
But I think that people that actually look at the docstring can if
not understand, have a nice idea of what the code does. Think that a large
sample app 'hands on' documentation  would benefit the community even
better and would be also a nice way to attract more dev's to the community.

**Comment by cenouro** [comment] 2015-10-20 19:25
@cescoferraro Another big advantage of sample apps is that a lot of "documentation" can be in the form of integration tests.

**Comment by orokusaki** [comment] 2015-11-03 02:23
+1 on this entire thread's existence - I've been checking back about once per month to see if Flask was still alive and kicking, since the time of the last release.

IMHO, releasing and fixing the docs incrementally will lead to more developers (Flask newcomers currently see that the last update was in 2013 and are probably fearful), which will lead to more contributors, which will lead to even better stability and performance, which obviously creates a positive feedback loop.

Agile works well for open source, and for the reasons I've mentioned. Letting updates pile up, undocumented, until 1.0, removes any of the benefits I just described. For instance, I haven't contributed to Flask, but that's not because I don't love at least the idea of Flask. It's because I haven't used Flask for a commercial project yet (so I'm only slightly acquainted with the code and ecosystem), which is because I'm fearful.

**Comment by jeffwidman** [comment] 2015-11-12 11:16
> And nobody likes writing documentation ;)

Actually, I enjoy it. About 80% of my PRs these days are fixing/enhancing docs for various projects, and it's rewarding to know that I'm making those projects more accessible for others. Nobody likes reading inconsistent/outdated docs. 

Personally though, I much prefer when a project is using RTD instead of a home-grown docs solution--I find it easier to navigate, simpler to contribute to because it's the same format as all the other RTD-based projects, and easier to cross-link stuff. I know @mitsuhiko said he isn't a fan of RTD, but if he was willing to reconsider I'd be willing to port them over.

**Comment by mitsuhiko** [comment] 2015-11-12 11:17
@jeffwidman can you clarify what you mean by that:

> simpler to contribute to because it's the same format as all the other RTD-based projects, and easier to cross-link stuff

**Comment by jeffwidman** [comment] 2015-11-12 11:49
1) Simpler to contribute because I'm just used to how RTD works... For most small changes, I can click 'Edit on Github' which drops me into the right source file and I can immediately edit and then submit a PR using Github's web ui... I can submit a PR fixing a typo in <2 mins because I don't have to poke around to locate the right source file or clone the repo locally. 
Similarly, I find the sidebars of most RTD themes visually easier to scan than the all black text across the page currently on the Flask docs--visually the current Flask docs are fine, but I do think the default RTD theme does a better job of using color hints for guiding the eyes. 

It's all trivial things, none of them huge, but they make for a more pleasant experience when I'm making small changes or skimming docs.

2) Re: cross-linking, I spoke quickly, and likely am wrong here. I forgot Flask docs are already using Restructured text, and already support inter-linking just fine. I actually don't know if RTD adds any custom syntax on top of RST for better interlinking among project pages, as pretty much the only time I use RST is on RTD projects... 

3) Additionally it's less maintenance, since you don't have to maintain a docs server, just let them handle it. I know it doesn't take you much time to maintain that server, but just overall it's one less thing to worry about. In general, I'm a fan of pushing these kinds of generic tasks onto others wherever possible, and from what I've seen, the Flask docs system doesn't currently have any UI customizations that aren't available in RTD. Plus you don't lose control of the docs because they're still in your repo and can switch back to your own sphinx build whenever you want.

**Comment by mitsuhiko** [comment] 2015-11-12 11:54
> For most small changes, I can click 'Edit on Github'

That's just a theme thing.  We could easily add this to our own theme.

> Similarly, I find the sidebars of most RTD themes visually easier to scan than the all black text across the page

Again, this is not a RTD but a theme thing.

> Re: cross-linking, I spoke quickly, and likely am wrong here. I forgot Flask docs are already using Restructured text, and already support inter-linking just fine.

It literally uses the same system: sphinx.

> Additionally it's less maintenance, since you don't have to maintain a docs server, just let them handle it.

Experience has shown that this is wrong, at least for the case of our own docs.  There is currently no reasonable way to build different branches on RTD with the same config without a lot of hackery.

**Comment by jeffwidman** [comment] 2015-11-12 12:10
Sounds fine. One question:

> There is currently no reasonable way to build different branches on RTD with the same config without a lot of hackery.

Can you clarify? I go to an RTD project and see "Latest | Stable | 2.0 | 1.9 | etc" 
What is it that you're wanting to do differently here?

**Comment by mitsuhiko** [comment] 2015-11-12 12:11
They all use the configuration that is baked into the checked out release.  Which means if you want to change the theme you need to commit it to all active branches (as an example).  This surfaces with older versions not linking to all the newer versions usually.

**Comment by lipis** [comment] 2015-12-07 00:03
Any Christmas gifts for this year?!

**Comment by ariscn** [comment] 2015-12-11 22:01
+1 to all the comments here.

@mitsuhiko The community wants to help, but you have to help us help you. It sounds like you're looking for a comprehensive documentation refresh. As described, that's too large a "feature" for people to help you. So:

a) Can you break "docs refresh" into smaller tasks?
b) Is there anything else on your Must Have list for 1.0?
c) Can you create a Github milestone for everyone to use as a list of TODOs?
d) Will you consider an interim 0.11 release to PyPi?

**Comment by rsyring** [comment] 2015-12-12 18:56
FWIW, I'd like to see an 11.0 release sooner with minimal documentation updates (state plainly it's a weakness).  Get the code out there.  Then rework the docs and website and that can be your 1.0 release.

By doing the release first and letting the docs catch up, people will then start using it and you will see, based on requests, what needs to be documented.  You will also see, I believe, more documentation PRs because people will run into unknowns, look at the code to figure out it out, and then write the docs they wished they had.

Not saying this is ideal...but, IMO, it's much better than waiting longer for a stable release.

**Comment by lipis** [comment] 2015-12-13 00:59
or `1.0.0-rc`.. there are ways to solve the whole thing.. and @rsyring is right.. once the version is there.. it's much much easier to fix the documentation.. :) all we need is one little edit button with a direct link to GitHub location of that snippet and all good!

**Comment by rsyring** [comment] 2015-12-14 18:49
FWIW, I think the 11.0 release would be preferable to an RC due to adoption differences.  With pip no longer installing dev releases by default, you would have a lot less people using an RC release.  If not-awesome docs are the only reason it's not 1.0, and not code quality, then more people using it == better situation IMO.

**Comment by lipis** [comment] 2015-12-14 18:54
> then more people using it == better situation IMO.

== much better situation. More people using it.. will have more reason to actually fix the documentation!

**Comment by sandys** [comment] 2016-01-12 18:37
hi guys,
is there any progress on this ? @mitsuhiko you had [mentioned](https://www.reddit.com/r/Python/comments/3xi6o9/whats_the_future_of_flask/cy4y3cd) on reddit about creating an org to share your workload. Is that still the plan ?

**Comment by mitsuhiko** [comment] 2016-01-12 18:40
Yes, that's the plan. I'm in the middle of it. Update very soon.

**Comment by sandys** [comment] 2016-01-12 18:48
@mitsuhiko thank you so much. a lot of us are really eager for it .

**Comment by jwogrady** [comment] 2016-01-12 18:49
If you like hirepython.com I'm happy to contribute the domain to your cause.

John

**Comment by lipis** [comment] 2016-01-21 10:07
:walking: :watch: :palm_tree:

**Comment by kingofhawks** [comment] 2016-02-16 03:03
+1 for new organization dedicated on flask:) Thanks @mitsuhiko

**Comment by ariscn** [comment] 2016-02-18 01:08
@mitsuhiko on Hacker News today:

> I'm (very slowly unfortunately) in the process of fixing this by restructuring the github org to get trusted contributors to fix this and to make it easier to have multiple smaller releases instead of a huge one. There is always risk in pushing out releases with a lot of changes which is what would happen which is why I want to have people in place that can push releases without my help to fix things if they are regressing.
I would have done it over Christmas already but life keeps happening and this is something I rather not do without having an action plan :)
Very soon now though.

**Comment by lipis** [comment] 2016-02-18 21:43
@ariscn an actual link to it would be nice..

**Comment by davidism** [comment] 2016-02-18 22:06
[story](https://news.ycombinator.com/item?id=11121355), [comment](https://news.ycombinator.com/item?id=11122750), [context](https://news.ycombinator.com/item?id=11121859).

**Comment by tebanep** [comment] 2016-02-27 13:33
+1 for a release candidate

**Comment by jigarmistry** [comment] 2016-03-03 11:24
> Yes, that's the plan. I'm in the middle of it. Update very soon.

When we can have updated info for this? I would like to be part of development process of flask (1.0,2.0)

**Comment by lipis** [comment] 2016-03-03 11:29
@jigarmistry I think it's planned for the summer of 2017..

**Comment by lipis** [comment] 2016-05-08 11:50
@ariscn  the first recorded _"very soon"_ by @mitsuhiko: https://github.com/pallets/flask/issues/1140#issuecomment-53157622

**Comment by L1ghtn1ng** [comment] 2016-05-22 12:59
@mitsuhiko any update?

**Comment by lipis** [comment] 2016-05-22 14:23
Christmas 2016 are not far.. actually they are coming every year.. :)

**Comment by jeffwidman** [comment] 2016-06-02 19:06
Now that we have Pallets as well as a recent Flask release, I'm closing this... we don't need an open issue to track progress when we already have the milestones in the issue tracker.

**Closed by jeffwidman** 2016-06-02 19:06 UTC
