### ISSUE TITLE
Docs are incorrect about how to run a debug server

### ISSUE THREAD

**Issue by roysmith** [pallets/flask#4928] opened 2022-12-26 19:42 UTC
> Python 3.9.13
> Flask 2.2.2
> Werkzeug 2.2.2
> 

The docs, in more than one place:

* https://flask.palletsprojects.com/en/2.2.x/quickstart/#debug-mode
* https://flask.palletsprojects.com/en/2.2.x/server/#command-line

say to run `flask run --debug` but that doesn't actually work:

```
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: No such option: --debug (Possible options: --debugger, --no-debugger)
```
You need to run `flask --debug run `

**Comment by davidism** [comment] 2022-12-26 20:25
Duplicate of the previous issue

**Closed by davidism** 2022-12-26 20:26 UTC
