### ISSUE TITLE
Multiple request headers with same name

### ISSUE THREAD

**Issue by Tyilo** [pallets/flask#850] opened 2013-08-27 15:33 UTC
I'm deploying my flask website to heroku and they pass 4 headers to flask: `X-Forwarded-For`, `X-Forwarded-Proto`, `X-Forwarded-Port` & `X-Request-Start`.

I want to use all of these headers in flask, however if there are multiple of these headers (except `X-Forwarded-For`) flask will only use the last ones, even when using `request.headers.get_all` or `request.headers.getlist`.

This is problematic as the client can easily fake these headers, which will override those values passed from heroku.

As the `request.headers` object is already the type `werkzeug.datastructures.EnvironHeaders`, which subclasses `werkzeug.datastructures.Headers`, which have support for a key with multiple values, I don't think it will be that hard to implement.

Example code:
`test.py`
```
import requests
from flask import Flask, request
app = Flask(__name__)

@app.route('/')
def test():
	k = 'X-Request-Start'
	h = request.headers
	print h.get(k)
	print h.get_all(k)
	print h.getlist(k)
	return 'Check the logs\n'

if __name__ == '__main__':
	app.run()
```

Testing:
```
python test.py &
curl -H 'X-Request-Start: test1' -H 'X-Request-Start: test2' http://127.0.0.1:5000/
```

Logs:
```
 * Running on http://127.0.0.1:5000/
test2
['test2']
['test2']
127.0.0.1 - - [27/Aug/2013 17:30:45] "GET / HTTP/1.1" 200 -
```

Expected result in logs:
```
 * Running on http://127.0.0.1:5000/
test2
['test1', 'test2']
['test1', 'test2']
127.0.0.1 - - [27/Aug/2013 17:30:45] "GET / HTTP/1.1" 200 -
```

**Comment by jvinet** [comment] 2015-04-03 22:45
@grampajoe, you treat multiple lines as if all values were included on one line.

Examples here: http://www.w3.org/Protocols/HTTP/HTRQ_Headers.html#z3

**Comment by mathiasbc** [comment] 2016-06-02 17:32
Still happening on flask version 0.11 although I agree that it should be a Heroku concern more than a feature of Flask.

**Comment by untitaker** [comment] 2016-06-02 17:36
I think we should close this because it's an issue with Heroku. Agreed?

**Comment by mathiasbc** [comment] 2016-06-02 17:44
+1

**Closed** 2016-06-03 09:00 UTC

**Comment by BartlomiejLewandowski** [comment] 2017-10-06 00:09
I'm using httpbin which is built on top of flask for integration testing. We've found a regression in one of our libraries which caused us to send multiple headers to a downstream service.

The idea was to use httpbin and flask to send back the headers received, but it turns out that this multiple header story is not supported by flask at all.

Is there any workaround for this?
