### ISSUE TITLE
slot definition of AppContext gives causes `assigning-non-slot` warning from pylint and mypy

### ISSUE THREAD

**Issue by hughsie** [pallets/flask#4038] opened 2021-05-13 13:08 UTC
> Describe how to replicate the bug.

I'm doing the fairly standard thing of adding a `g.user` property on the appcontext in my app, but `pylint` is complaining with:

    Assigning to attribute 'user' not defined in class slots (assigning-non-slot)

Ignoring the pylint warning makes mypy complain very loudly error:

    "AppContext" has no attribute "user"

This can be reproduced using the docs https://flask.palletsprojects.com/en/2.0.x/appcontext/#storing-data, which tell the user to store the `db` on `g` using: `g.db = connect_to_database()`.

If we're not supposed to be setting random properties there any more then the docs probably need fixing. maybe we're supposed to use `db = g.setdefault("db", connect_to_database())` now?

- Python version: `2.0.0`
- Flask version: `3.9.4`

**Comment by ThiefMaster** [comment] 2021-05-13 13:10
This looke like a duplicate of #4020

**Closed by ThiefMaster** 2021-05-13 13:10 UTC

**Comment by davidism** [comment] 2021-05-13 13:13
`_AppCtxGlobals` doesn't set `__slots__`, but it looks like the type of `flask.globals.g` is incorrectly marked as `AppContext` (which also doesn't define slots, so not sure why that's the error).

**Comment by davidism** [comment] 2021-05-13 13:14
I'll reopen the original issue, this is still a duplicate. Thanks for reporting it.
