### ISSUE TITLE
redirect is annotated to return a werkzeug type

### ISSUE THREAD

**Issue by tucked** [pallets/flask#5001] opened 2023-02-24 21:35 UTC
My app doesn't need `werkzeug` directly except for type annotations of views that contain a `redirect` call, even when I explicitly provide `Response=flask.Response`.
https://github.com/pallets/flask/blob/5cdfeae2e82541577e17f5179d91775550e34ebd/src/flask/helpers.py#L233-L235
I think this can be achieved in a similar way to `classmethod`s:
``` python
_BaseResponse = t.TypeVar("_BaseResponse", bound="BaseResponse")

def redirect( 
    location: str, code: int = 302, Response: t.Optional[t.Type[_BaseResponse]] = None 
) -> _BaseResponse:
```

**Comment by davidism** [comment] 2023-02-24 21:53
Duplicate of https://github.com/pallets/flask/issues/4976

**Closed by davidism** 2023-02-24 21:53 UTC
