### ISSUE TITLE
No auth keyword arg in the test client for Basic HTTP Auth 

### ISSUE THREAD

**Issue by DunkeeFunk** [pallets/flask#3160] opened 2019-04-23 19:11 UTC
### Expected Behavior

I was trying to write unit tests for my flask restful api which uses BasicHttpAuth on the initial request and returns a JWT token. All subsequent requests have this token in an x-access-header up to an expiry of 15 mins, then re-authentication happens( the code for this is in the anacropapi repo on my profile under api.__init__.py). I have noted the error in the template. I thought this test client would be fully compatible with the requests package. Does anyone know of a work around for this or can an auth keyword arg be added ?

```python
import unittest 

class ApiTest(unittest.TestCase): 

    def setUp(self):
        # creates a test client
        self.app = app.test_client()
        # add a user into the account code goes here ...

    def tearDown(self):
        db.drop_all()
        # etc...

    def test_login(self):
        # sends HTTP GET request to the application
        # on the specified path with an auth kwarg passed like in requests 
         result = self.app.get('/login', auth=requests.auth.BasicHttpAuth(username, password)) 
```

### Actual Behavior

```pytb
this returns no auth arg found error i cant remember the specfic error off hand 
```

### Environment

* Python version: 3.6
* Flask version: latest
* Werkzeug version: latest

**Comment by davidism** [comment] 2019-04-23 19:17
Duplicate of https://github.com/pallets/werkzeug/issues/1376

**Closed by davidism** 2019-04-23 19:17 UTC
