### ISSUE TITLE
Using getlist for files is never empty?

### ISSUE THREAD

**Issue by aaveidt** [pallets/flask#3342] opened 2019-08-24 20:31 UTC
I want to get file list from form by using:

`photos = request.files.getlist("photo")
`
However if i haven't select anything, the photos value is never be [] like other fields.

So the way to check for empty field is failed:

```
if not photos:
   pass
```
The result for empty form is:
` [<FileStorage: '' ('application/octet-stream')>]`

How do i get rid of it?

**Comment by davidism** [comment] 2019-08-24 21:07
Duplicate of #3130 

> `request.files` always has whatever is submitted. You can do `request.files["secondfile"].filename` == ""`, or look at its size. But it was still submitted, just with an empty filename and no data. Again, that's just what HTML forms do.

https://github.com/pallets/flask/issues/3130#issuecomment-476765447

**Closed by davidism** 2019-08-24 21:07 UTC
