### ISSUE TITLE
Async class based view causes crash

### ISSUE THREAD

**Issue by TimPansino** [pallets/flask#4126] opened 2021-06-03 21:25 UTC
## The Bug
* `flask.views.View` does not properly handle conversion of an async `dispatch_request`, resulting in a coroutine that is never awaited.
* `flask.views.MethodView` does not properly handle conversion of async methods, resulting in coroutines that are never awaited.

## Replication

1. Create an async `dispatch_request` method on a `View`, or a `get` method on a `MethodView`.
1. Add the view to the app using the `View.as_view()` and `app.add_url_rule()` functions.
1. Access the route and observe a crash and 500 status code.

The following application reproduces the bug.

```python
from flask import Flask
from flask.views import View, MethodView

app = Flask("MyApp")

class TestAsyncView(View):
    async def dispatch_request(self):
        return 'ASYNC VIEW RESPONSE'

class TestAsyncMethodView(MethodView):
    async def get(self):
        return 'ASYNC METHODVIEW GET RESPONSE'

app.add_url_rule("/async_view", view_func=TestAsyncView.as_view("test_async_view"))
app.add_url_rule('/async_methodview', view_func=TestAsyncMethodView.as_view('test_async_methodview'))

if __name__ == "__main__":
    app.run(port=8000)
```

The following error occurs after running `curl localhost:8000/async_view`:

```
Traceback (most recent call last):
  File "/Users/tpansino/NewRelic/Testing/Flask2Bug/flask/src/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tpansino/NewRelic/Testing/Flask2Bug/flask/src/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/tpansino/NewRelic/Testing/Flask2Bug/flask/src/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/Users/tpansino/NewRelic/Testing/Flask2Bug/flask/src/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.
```

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

## Expected Behavior
* Asynchronous `dispatch_request` functions and methods should either be:
  * Converted using `async_to_sync` before being returned from `as_view()`.
  * Executed or awaited in the application when a route is accessed.

## Environment

- Python version: 3.9.5
- Flask version: 2.0.1

**Comment by miguelgrinberg** [comment] 2021-06-03 22:49
Duplicate of https://github.com/pallets/flask/issues/4112. The fix is coming with the next release in the 2.0.x line.

**Closed** 2021-06-03 22:59 UTC
