### ISSUE TITLE
CLI fails during create database in Flaskr tutorial

### ISSUE THREAD

**Issue by vanflymen** [pallets/flask#1949] opened 2016-07-07 18:40 UTC
When following the tutorial, I could not run `$ flask initdb`. 

```
Traceback (most recent call last):
  File "/Users/dvf/environments/flaskTutorial/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/dvf/environments/flaskTutorial/lib/python2.7/site-packages/flask_cli/cli.py", line 502, in main
    cli.main(args=args, prog_name=name)
  File "/Users/dvf/environments/flaskTutorial/lib/python2.7/site-packages/flask_cli/cli.py", line 369, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/dvf/environments/flaskTutorial/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/dvf/environments/flaskTutorial/lib/python2.7/site-packages/click/core.py", line 1055, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/dvf/environments/flaskTutorial/lib/python2.7/site-packages/click/core.py", line 1094, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/dvf/environments/flaskTutorial/lib/python2.7/site-packages/flask_cli/cli.py", line 340, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/Users/dvf/environments/flaskTutorial/lib/python2.7/site-packages/flask_cli/cli.py", line 226, in load_app
    rv = locate_app(self.app_import_path)
  File "/Users/dvf/environments/flaskTutorial/lib/python2.7/site-packages/flask_cli/cli.py", line 90, in locate_app
    __import__(module)
ImportError: No module named flaskr
```

This was fixed by changing the environment variable to:

    export FLASK_APP=flaskr.py

On OS X 10.11.3 and Python 2.7.12

**Comment by nateprewitt** [comment] 2016-07-07 18:46
This looks like it may be a duplicate of  #1902.

**Closed** 2016-07-07 19:19 UTC
