### ISSUE TITLE
blueprint_register with two different controller with subdomain but url_for use first problem

### ISSUE THREAD

**Issue by broject** [pallets/flask#2660] opened 2018-03-16 08:59 UTC
from app.controllers.dashboard.admin import dashboard1
from app.controllers.dashboard.supply import dashboard2

app.register_blueprint(dashboard1, subdomain='admin')
app.register_blueprint(dashboard2, subdomain='supply')

but 

@dashboard2.route('/')
def index():
       return url_for('company.index') 
is always appear that "http://admin.domain.com:5000/company"

**Comment by davidism** [comment] 2018-03-16 12:11
Duplicate of #1091

**Closed by davidism** 2018-03-16 12:11 UTC
