### ISSUE TITLE
`click.get_current_context()` returns `None` after reload

### ISSUE THREAD

**Issue by reubano** [pallets/flask#4460] opened 2022-02-23 00:59 UTC
Following the guidelines in https://github.com/pallets/flask/issues/3552, `click.get_current_context()` returns an empty `ctx` when the [Flask app reloads](https://stackoverflow.com/questions/28241989/flask-app-restarting-with-stat) (this is due to the [thread switching](https://click.palletsprojects.com/en/8.0.x/advanced/#global-context-access)).

```python
from threading import get_native_id
from click import get_current_context

def create_app(*args, **kwargs):
    ctx = get_current_context(silent=True)
    print(get_native_id(), ctx)
```

```bash
flask run -p 5001
 * Environment: development
 * Debug mode: on
2537498, <click.core.Context object at 0x104a98490>
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
 * Restarting with stat
2537262, None
 * Debugger is active!
 * Debugger PIN: 271-523-819
```

Notice how after `Restarting with stat`, `ctx` is now `None`.

Since passing `script_info` to the app factory was deprecated, the work-a-round should also work on app restarts just like the deprecated workflow does.

Environment:

- Python version: 3.9.10
- Flask version: 2.0.3

**Comment by davidism** [comment] 2022-02-23 01:02
I don't understand the issue being described. A restart restarts the entire process, state was never preserved between restarts. When opening an issue, be sure to include enough detail so that we can accurately understand and reproduce the issue.

**Comment by reubano** [comment] 2022-02-23 01:04
To clarify, this is [app reloading](https://stackoverflow.com/questions/28241989/flask-app-restarting-with-stat), not manual restarting.

**Comment by davidism** [comment] 2022-02-23 01:05
Yes, app reloading restarts the process.

**Comment by reubano** [comment] 2022-02-23 01:06
```python
def create_app(*args, **kwargs):
    ctx = get_current_context(silent=True)
    print(ctx)
```

```bash
manage run -p 5001
 * Environment: development
 * Debug mode: on
<click.core.Context object at 0x104a98490>
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
 * Restarting with stat
None
 * Debugger is active!
 * Debugger PIN: 271-523-819
```

**Comment by davidism** [comment] 2022-02-23 01:08
What is `manage`?

**Comment by reubano** [comment] 2022-02-23 01:10
https://pypi.org/project/manage.py/.... basically Django style `manage` commands. I use `manage` instead of `flask` or `python manage.py`

**Comment by davidism** [comment] 2022-02-23 01:11
That library was last released in 2015, and the GitHub page doesn't exist. It's not part of Flask.

**Comment by davidism** [comment] 2022-02-23 01:22
This is because the app is lazy-loaded, which happens in a separate thread. Click's context is thread-local, so the thread that calls `create_app` doesn't have access to the context. You can continue using the context by disabling lazy loading, at the expense of the reloader not handling syntax errors. `flask run --eager-loading`

Part of the point of removing `script_info` is that it's essentially an internal part of the Flask CLI, not something that can be relied on, since it won't be available in production.

**Closed** 2022-02-23 03:13 UTC
Labels: cli
