### ISSUE TITLE
Request | request.files access is too slow.

### ISSUE THREAD

**Issue by kshitij12345** [pallets/flask#3546] opened 2020-03-27 14:31 UTC
### Expected Behavior

I am getting very slow access to `request.files['file']`.
Below is a part of the code.
```python
@app.route('/perspective_transform/', methods = ['POST'])
def perspective_transform():
    print(request)
    with Timer(prefix='API Execution'):
        with Timer(prefix='Loading Image File'):
            file = request.files['file']
            
        with Timer(prefix='Read File'):
            img_bytes = file.read()

        with Timer(prefix='Loading Args'):
            vertices = request.form.get('vertices')

        # Some other processing code
    return response
```
I would think that once request reaches the Python function, all data is available at that point.
Surprisingly most of the time is spent at `file = request.files['file']`
Based on my assumption it should be quick. Also the `print(request)` doesn't take any time at all.
The `file` that I am trying to get is generally in the range 1Mb to 2Mb.
On some occassion it takes very very long. 
Is this the expected behavior?
Any way to mitigate it?
```
Loading Image File took 0.423 seconds
Read File took 0.001 seconds
Loading Args took 0.000 seconds
API Execution took 0.736 seconds
```
### Environment

* Python version: 3.7
* Flask version: 1.1.1 
* Werkzeug version: 1.0.0

**Comment by davidism** [comment] 2020-03-27 14:34
Duplicate of pallets/werkzeug#875

**Closed by davidism** 2020-03-27 14:34 UTC

**Comment by cauffe** [comment] 2020-03-27 15:15
Dhdhdhd

**Comment by ThiefMaster** [comment] 2020-03-27 15:17
@cauffe Don't do that again.

**Comment by kshitij12345** [comment] 2020-03-27 16:00
@davidism Thanks for the reference and quick reply.
