### ISSUE TITLE
flask.redirect fails on audio file upload.

### ISSUE THREAD

**Issue by viper6277** [pallets/flask#2803] opened 2018-05-28 04:56 UTC
I have a setup where one route behaves as a form processor for various forms. Under the normal circumstance of uploading an audio file... (mp3)... I would be using "flask.request.files" to process this file.

But what if I do not have any forms on the site that upload files... what I have noticed and provided a file for to duplicate the issue ... is in the event of an audio file POST upload to a form processor that does not have a control to process files... ie "flask.request.files".... the "flask.redirect([route])" fails... 

Line 61 of the sample file is purposely left commented out...to demonstrate the redirect failure... by removing comment and enabling ..."posted_files = flask.request.files" .... the redirect magically works again...

There seems to be an issue in the fact that an audio file is being posted... the same test run with images file formats entered into line 40.....ie.... accept=".jpg, .png" do not effect the redirect... 

[flask_error.zip](https://github.com/pallets/flask/files/2043603/flask_error.zip)

In case anyone is interested.... I'm running Flask v1.0.2 on Python v3.6.3

**Comment by davidism** [comment] 2018-05-28 05:04
Duplicate of pallets/werkzeug#1313

**Closed by davidism** 2018-05-28 05:04 UTC
