### ISSUE TITLE
Flask does not detect route collisions between blueprints and app

### ISSUE THREAD

**Issue by davejohncole** [pallets/flask#2260] opened 2017-04-27 04:29 UTC
The following program demonstrates the effect of defining the same route across blueprints and the app - fetch http://localhost:5678/hello for each run:
```
$ python server.py app app
$ python server.py bp
$ python server.py app
$ python server.py app bp
$ python server.py bp app
$ python server.py bp app bp
```

It surprised me that Flask does not report route collisions.
```
import sys
from flask import Flask, Blueprint


def main():
    bp_num = 1
    app = Flask(__name__)
    for arg in sys.argv:
        if arg == 'bp':
            bp_name = 'bp%d' % bp_num
            bp_num += 1
            bp = Blueprint(bp_name, __name__)

            @bp.route('/hello')
            def hello_bp():
                return 'Hello ' + bp_name
            app.register_blueprint(bp)

        if arg == 'app':
            @app.route('/hello')
            def hello():
                return 'Hello'

    app.run(host='0.0.0.0', port=5678)


if __name__ == '__main__':
    main()
```

**Comment by davidism** [comment] 2017-04-27 11:42
Duplicate of #1568, but this is an issue with Werkzeug, not Flask.

**Closed by davidism** 2017-04-27 11:42 UTC
