### ISSUE TITLE
App run with debug mode raise OSError

### ISSUE THREAD

**Issue by khs123** [pallets/flask#3133] opened 2019-03-29 03:55 UTC
### Expected Behavior

App run with debug mode raise OSError
```python
app = make_app()
celery = make_celery(app)
KafkaProducerExt(app)
if __name__ == "__main__":
    app.run(debug=True)

```

### Actual Behavior

App run with debug mode raise OSError, when i change debug to False, everything ok
```pytb
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "app/app.py", line 8, in <module>
    app.run(debug=True)
  File "/home/khanhdv/.virtualenvs/api_jd/lib/python3.5/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/home/khanhdv/.virtualenvs/api_jd/lib/python3.5/site-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/home/khanhdv/.virtualenvs/api_jd/lib/python3.5/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/home/khanhdv/.virtualenvs/api_jd/lib/python3.5/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

```

### Environment

* Python version: Python 3.5.2 
* Flask version:1.0.2
* Werkzeug version:0.15.1

**Comment by davidism** [comment] 2019-03-29 04:09
Duplicate of pallets/werkzeug#1482. You've marked a script as executable but didn't add an exec comment at the top. Either add `#! /usr/bin/env python` or unset the executable bit.

**Closed by davidism** 2019-03-29 04:09 UTC

**Comment by aaveidt** [comment] 2019-04-13 19:40
@davidism after adding above line, i got `env: python\r: No such file or directory`

**Comment by liangbaochuan** [comment] 2019-06-07 06:25
> @davidism after adding above line, i got `env: python\r: No such file or directory`

i met same problem with u, has been solved it ?

**Comment by aspiringguru** [comment] 2019-11-18 00:17
> use the recommended `flask run` command to run the development server.
https://flask.palletsprojects.com/en/1.0.x/cli/
