### ISSUE TITLE
Body of 412 responses not sent

### ISSUE THREAD

**Issue by eruvanos** [pallets/flask#2576] opened 2018-01-03 17:09 UTC
### Expected Behaviour

Body of a 412 response should be included on all Platforms. 
(Works on OS X, but not on linux system)

```python
from flask import Flask
app = Flask(__name__)
@app.route('/')
def r():
    return 'This should be visible\n', 412
app.run('0.0.0.0', port=8080)
```

```shell
curl localhost:8080

# Expected:
# > 127.0.0.1 - - [03/Jan/2018 17:00:15] "GET / HTTP/1.1" 412 -
# > This should be visible
```

### Actual Behavior

The response does have an empty body if executed on a linux system. (docker-image python)

```shell
curl localhost:8080

# Actual:
# > 127.0.0.1 - - [03/Jan/2018 17:00:15] "GET / HTTP/1.1" 412 -
```

### Environment

* Python version: 3.6.4
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment] 2018-01-03 19:04
Duplicate of pallets/werkzeug#1231

**Closed by davidism** 2018-01-03 19:04 UTC
