### ISSUE TITLE
use http1.1 keepalive get method not allowed error

### ISSUE THREAD

**Issue by peterpuppy** [pallets/flask#4549] opened 2022-04-25 09:41 UTC
use http1.1 keepalive get method not allowed error

this can be fixed by use
`WSGIRequestHandler.protocol_version="HTTP/1.0"`

and appear when use
`WSGIRequestHandler.protocol_version="HTTP/1.1"`

it seem a http server bug

Environment:

- Python version:3.8
- Flask version:2.1.1

**Comment by peterpuppy** [comment] 2022-04-25 09:46
maybe the same problem 
https://github.com/pallets/werkzeug/issues/2380

**Comment by davidism** [comment] 2022-04-25 13:12
Duplicate of https://github.com/pallets/flask/issues/4507, https://github.com/pallets/werkzeug/issues/2380, and many more. Be sure to check closed issues before opening a new one. Don't use the development server in production.

**Closed by davidism** 2022-04-25 13:12 UTC

**Comment by davidism** [comment] 2022-04-28 16:54
This will addressed by https://github.com/pallets/werkzeug/issues/2397, but reconsider why you're making a post request with form data then not reading that form data. Also note that the development server is not intended for production. Any production WSGI server handles this correctly already.
