### ISSUE TITLE
Jsonify does not take allow_nan

### ISSUE THREAD

**Issue by david-cortes** [pallets/flask#3083] opened 2019-01-25 13:43 UTC
It seems passing argument `allow_nan = False` to `flask.jsonify` will not actually turn `NaN`s into something else like `null` - e.g. `flask.jsonify({“a” : numpy.nan})` will produce `{“a” : NaN}`

**Comment by davidism** [comment] 2019-01-25 13:55
Duplicate of #2832

**Closed by davidism** 2019-01-25 13:55 UTC
