### ISSUE TITLE
Automatic redirect with "/" breaks routes with different methods

### ISSUE THREAD

**Issue by JelteF** [pallets/flask#1783] opened 2016-04-16 11:59 UTC
I have found an issue that is caused by the automatic redirect of routes to the version with a "/" at the end. See the code below for a minimal example:
```python
from flask import Flask
app = Flask(__name__)


@app.route("/a/", methods=["GET"])
def hello():
    return "Hello GET!\n"


@app.route("/a", methods=["POST"])
def hello_post():
    return "Hello POST!\n"

if __name__ == "__main__":
    app.run()

```
The POST route is unreachable as the "/" redirect is done without looking at the method. See the following curl commands (the `-L` flag is to follow redirects):

```bash
$ curl localhost:5000/a/
Hello GET!

$ curl localhost:5000/a
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://localhost:5000/a/">http://localhost:5000/a/</a>.  If not click the link.

$ curl localhost:5000/a -L
Hello GET!

$ curl localhost:5000/a -X POST
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://localhost:5000/a/">http://localhost:5000/a/</a>.  If not click the link.

$ curl localhost:5000/a/ -X POST
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

$ curl localhost:5000/a -X POST -L
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

Edit: My python version is Python3.4 and Werkzeug is 0.11.8 but it was also possible with the git version of Werkzeug.

**Comment by JelteF** [comment] 2016-04-16 12:38
Switching the order of the two routes fixes the issue btw:
```python
from flask import Flask
app = Flask(__name__)


@app.route("/a", methods=["POST"])
def hello_post():
    return "Hello POST!\n"

@app.route("/a/", methods=["GET"])
def hello():
    return "Hello GET!\n"

if __name__ == "__main__":
    app.run()

```

That way POST does get matched:
```bash
$ curl localhost:5000/a -L
Hello GET!
$ curl localhost:5000/a -X POST -L
Hello POST!
```

**Comment by ThiefMaster** [comment] 2016-04-16 12:40
Mixing `/a/` and `/a` seems like a really bad idea to me. Try `app.route(.., strict_slashes=False)` to disable the automated redirect from `/a` to `/a/` if you really need it though.

If that solves it for you I'd say it's not a bug.

**Comment by JelteF** [comment] 2016-04-16 12:50
I agree that it is not very nice. But I found this bug during a refactor that had the side of importing the routes in a different order and suddenly different parts of my application were broken because there were some GET routes that redirected my PUT routes. It seems bad that routes are redirected when the resulting route will result in a 405 error, especially when the first route was in the routing table for that method.

Disabling strict slashes for the GET route in the example works `strict_slashes`, but this is not really what I want since like strict slashes and have them enabled for a reason.

**Comment by AzureusNation** [comment] 2016-04-16 17:22
Hello @JelteF 
Really this is bad practice. I'll show you a method that will solve this issue for you.

```python
from flask import Flask, request

app = Flask(__name__)


@app.route("/hello", methods=["GET", "POST"])
def hello():
    if request.method == "POST":
        return "Hello POST!"
    return "Hello GET!"


if __name__ == '__main__':
    app.run()
```

I always put both get and post in to one method. It's best practice and it keeps your code really clean and easy to read.

**Comment by JelteF** [comment] 2016-04-16 17:46
@AzureusNation When using REST like applications I think it is a very weird practice to do it like this. Since the GET, PUT and POST methods probably do entirely different things, but putting them in the same function. It is also shown in examples that you can simple have functions with the same route but with different methods:
http://flask.pocoo.org/snippets/1/

I've also used this method for more than two years now and have never had any problems with it except the one I'm showing here.

**Comment by ThiefMaster** [comment] 2016-04-16 17:48
You could use class-based views or an extension like flask-restful

**Comment by AzureusNation** [comment] 2016-04-16 17:54
@JelteF Here's an idea so not all the code is in the same function. You could have your functions in a separate py file and call the functions like this.

```python
@app.route("/hello", methods=["GET", "POST"])
def hello():
    if request.method == "POST":
        return doPost()
    return doGet()

**Comment by ThiefMaster** [comment] 2016-04-16 17:56
Pretty ugly IMO (not to mention that camelCase doesn't belong into python code).

**Comment by jeffwidman** [comment] 2016-04-17 20:26
It doesn't look like there's a bug here. Having the strict slashes redirect default to on seems fine to me--I prefer that we have a redirect one way or the other as I think it leads to cleaner URLs by default. If a user for some reason wants to mix the route styles, it's not hard to google how to turn off that redirect.

**Comment by JelteF** [comment] 2016-04-17 20:51
The redirect itself is not the problem, since that is exactly what I want. The problem is that it redirects even though the method is invalid after the redirect, especially because the exact route is valid for that method. If a GET route would be defined with and without a slash I would argue that this behaviour is not a bug. But in this case a redirect is done to a route that will definitely return an error in favour of not redirecting and having a route that matches directly.

**Comment by untitaker** [comment] 2016-04-17 21:12
FTR changing the evaluation order to anything "complexity-based" seems like a no-go to me since the resulting behavior would be harder to reason about. You're going to end up with edgecases like this one either way: I think the current way has fewer ones. Also it's easier to tweak for edgecases.

**Comment by jeffwidman** [comment] 2016-04-18 20:40
Having thought about this more, I agree the behavior is definitely surprising and does feel like a bug. If a route doesn't define a HTTP method, then another route that handles that method shouldn't be overridden, regardless of auto-redirects. 

I'm not sure how to best solve it. Probably the redirect should only kick in for the defined HTTP methods on a route. That's the behavior I would expect.

**Comment by untitaker** [comment] 2016-04-18 20:44
Sorry, yes, that *is* a bug. I didn't even sense this from the original post, probably was half-sleeping.

While I think this can *maybe* be solved in a backwards-compatible manner, I don't think it qualifies as a bugfix release, as it *might* break applications.

**Comment by JelteF** [comment] 2016-04-19 18:16
Glad to hear you guys agree. After looking into to Flask internals a bit I think this is actually a Werkzeug bug instead of a Flask bug.

**Comment by JelteF** [comment] 2016-04-19 18:51
I've just submitted a very simple pull request in the werkzeug repo to fix this bug. https://github.com/pallets/werkzeug/pull/907

**Comment by jeffwidman** [comment] 2016-04-19 19:23
Closing, this is now tracked over in https://github.com/pallets/werkzeug/pull/907

Thanks again @JelteF for working on this.

**Comment by untitaker** [comment] 2016-04-19 19:29
no please keep this issue open, PRs are different from issues.

**Comment by jeffwidman** [comment] 2016-04-19 20:34
No problem, but I thought the switch to fixing this in Werkzeug means it's not an issue with Flask but with upstream? Do we keep Flask issues open if the underlying problem is in a dependancy?

**Comment by untitaker** [comment] 2016-04-19 20:39
It would be better refiled against Werkzeug but more importantly, some issue should stay open.

**Comment by mitsuhiko** [comment] 2016-05-22 10:20
I would close this and file it again against Werkzeug. This actually is also related to this issue: https://github.com/pallets/werkzeug/issues/185

(As the flipping of the order of the decorator should not have made a difference)

**Closed by mitsuhiko** 2016-05-22 10:20 UTC
