### ISSUE TITLE
test_main_module_paths fails on RHEL and Ubuntu when using Amazon EC2

### ISSUE THREAD

**Issue by karlw00t** [pallets/flask#1879] opened 2016-06-03 18:56 UTC
Running the unit tests against HEAD (e048aa4e19), I'm able to reproduce a single failing unit tests in:
> tests/test_instance_config.py::test_main_module_paths

I'm able to reproduce the bug on Amazon Linux 2016.03.1 and RHEL 7.2.  I'm running on a fresh EC2 instance in both cases, and the steps to reproduce are the same, here is my bash history:

> sudo yum install python-virtualenv
> sudo yum groupinstall 'Development Tools'
> virtualenv flask
> cd flask/
> git clone https://github.com/pallets/flask.git
> cd flask/
> source ../bin/activate
> pip install -e .
> pip install -r test-requirements.txt 
> py.test tests/test_instance_config.py::test_main_module_paths

failing output:

> modules_tmpdir = local('/tmp/pytest-of-ec2-user/pytest-0/test_main_module_paths0/modules_tmpdir'), purge_module = <function inner at 0x170c1b8>
> 
>     def test_main_module_paths(modules_tmpdir, purge_module):
>         app = modules_tmpdir.join('main_app.py')
>         app.write('import flask\n\napp = flask.Flask("__main__")')
>         purge_module('main_app')
>     
>         from main_app import app
>         here = os.path.abspath(os.getcwd())
> >       assert app.instance_path == os.path.join(here, 'instance')
> E       assert '/home/ec2-us...r/py-instance' == '/home/ec2-use...lask/instance'
> E         - /home/ec2-user/flask/var/py-instance
> E         ?                      ^ ^ ---
> E         + /home/ec2-user/flask/flask/instance
> E         ?                      ^^ ^^
> 
> tests/test_instance_config.py:33: AssertionError

This test seems to be passing fine on Travis, and on Debian and OSX.  It appears to be a Redhat/Amazon Linux specific issue.  I ran `git bisect` back to commits on May 26th, 2016 and the test still fails all attempts.

**Comment by untitaker** [comment] 2016-06-03 19:27
I'm sorry, but what am I supposed to do?

**Comment by untitaker** [comment] 2016-06-03 19:27
Are you sure that you installed Flask on both machines the same way? What are the respective setuptools, pip and Python versions?

**Comment by jeffwidman** [comment] 2016-06-03 19:42
Sorry, I should have added context. This is a Pycon sprinter who hit this issue and works at Amazon. While the root cause is likely upstream, since he'd done all the research and had a clearly reproducible test case, I suggested he add it to the tracker so that we can let it float a little and see if anyone else has a suggested fix that doesn't feel too hacky. So I'd just let this float for a bit and if no one else hits it we can close it down the road.

**Comment by karlw00t** [comment] 2016-06-03 22:16
I ran this on Ubuntu (trusty-14.04) on an EC2 instance as well and was able to reproduce this:

> sudo apt install build-essential
sudo apt install python-virtualenv
virtualenv flask
cd flask/
source bin/activate
sudo apt install git
git clone https://github.com/pallets/flask.git
cd flask/
pip install -e .
pip install -r test-requirements.txt 
py.test

The error that I'm getting is in the same function, same line.

**Comment by karlw00t** [comment] 2016-06-03 22:21
Version numbers from the Ubuntu host:

>(flask)ubuntu@ip-172-31-12-20:~/flask/flask$ pip --version
pip 1.5.4 from /home/ubuntu/flask/local/lib/python2.7/site-packages (python 2.7)
(flask)ubuntu@ip-172-31-12-20:~/flask/flask$ python --version
Python 2.7.6
(flask)ubuntu@ip-172-31-12-20:~/flask/flask$ python -m easy_install --version
setuptools 2.2

**Comment by davidism** [comment] 2016-09-21 17:55
#2035 jogged my memory of and old issue I helped someone debug.  The env should be inside the project, but you've checked out the project inside the env.  This makes Flask think that it's installed rather than running locally.

**Closed** 2016-09-21 18:42 UTC
Labels: packaging, question

**Comment by begueradj** [comment] 2017-05-11 16:19
I have this same problem (test_instance_config.py:33: AssertionError) with the current Flask version. Environment is:
- Ubuntu 16.04 LTS
- Python 3.5.2 
- pytest version 3.0.7

`ls` inside the virtual environment outputs this: `ls
bin  flask  include  lib  pip-selfcheck.json
`
How to fix this?

**Comment by davidism** [comment] 2017-05-11 16:23
Don't put the flask dir in your env dif, put your env dir in the flask dir (or completely separate).
