### ISSUE TITLE
ImportError: cannot import name 'Markup' from 'flask'

### ISSUE THREAD

**Issue by MrBird88** [pallets/flask#5088] opened 2023-04-25 21:28 UTC
I want to start by apologizing in advance if I make any mistakes in this bug report, I'm new to development and any mistakes are unintentional. That being said I appreciate any input as to how I can improve.

# The issue: #
Creating a class that inherits from FlaskForm causes an error with the following traceback
```
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/rburd/.local/share/virtualenvs/d5-9RMvys9g/lib/python3.11/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/home/rburd/academy/Mod-6/w18/d5/app/__init__.py", line 2, in <module>
    from .form import Tweet
  File "/home/rburd/academy/Mod-6/w18/d5/app/form.py", line 1, in <module>
    from flask_wtf import FlaskForm
  File "/home/rburd/.local/share/virtualenvs/d5-9RMvys9g/lib/python3.11/site-packages/flask_wtf/__init__.py", line 4, in <module>
    from .recaptcha import Recaptcha
  File "/home/rburd/.local/share/virtualenvs/d5-9RMvys9g/lib/python3.11/site-packages/flask_wtf/recaptcha/__init__.py", line 1, in <module>
    from .fields import RecaptchaField
  File "/home/rburd/.local/share/virtualenvs/d5-9RMvys9g/lib/python3.11/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/home/rburd/.local/share/virtualenvs/d5-9RMvys9g/lib/python3.11/site-packages/flask_wtf/recaptcha/widgets.py", line 2, in <module>
    from flask import Markup
ImportError: cannot import name 'Markup' from 'flask' (/home/rburd/.local/share/virtualenvs/d5-9RMvys9g/lib/python3.11/site-packages/flask/__init__.py)
```
If I switch to flask ver. 2.2.3 I receive no such error

# How to reproduce: #
Start a new project in an empty directory using the command `pipenv install flask flask-wtf python-dotenv`
Create a subfolder named 'app' with the following files
```python
# /app/__init__.py
from flask import Flask
from .form import Tweet

app = Flask(__name__)

```

and

```python
# /app/form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField

class Tweet(FlaskForm):
    author = StringField("Author")
    submit = SubmitField("Create New Tweet")
```

Create a .flaskenv file with the following contents:
```
FLASK_APP=app
```

Finally try to start the app with the command `pipenv run flask run`

# What I Expected: #
When the `flask run` command is given no error should occur, which is the behavior observed when using flask ver. 2.2.3

Environment:

- Python version: 3.11.3
- Flask version: 2.3.0

**Comment by davidism** [comment] 2023-04-25 21:38
Duplicate of https://github.com/pallets/flask/issues/5084

**Closed** 2023-04-25 21:38 UTC
