### ISSUE TITLE
Incorrect handling of filename* in Content-Disposition header causes a double quote to appear at the end of a non-ASCII file name

### ISSUE THREAD

**Issue by itsjef** [pallets/flask#3638] opened 2020-06-04 09:27 UTC
### Issue Description
When uploading a file from Postman, if the file name contains non-ascii characters, a double quote will be appended at the end of it. Such issue doesn't happen if the file is uploaded from a web-form or using a CLI tool.

![image](https://user-images.githubusercontent.com/1902587/83736584-0fd51600-a67c-11ea-90e0-a800a7ced5c9.png)

Ref: https://github.com/postmanlabs/postman-app-support/issues/8537

### Expected Behavior
File name will remain unchanged (red circle) as when I uploaded it from a web-form, or using a CLI tool (cURL, httpie)

### Actual Behavior
A double quote symbol got appended to the file name (blue circle).

### Source code
```python
from flask import Flask, request

app = Flask(__name__)


@app.route("/", methods=["POST"])
def upload_file():
    print("request.files:", request.files)
    return ""


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=4444)
```

### Environment

* Python version: 3.6, 3.7 and 3.8
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by jab** [comment] 2020-06-04 13:51
Thanks for reporting this. Based on the referenced Postman issue, the problem is caused by incorrect handling of `filename*=...` (without following that link it isn’t clear from the issue description that this isn’t a bug in Postman).

**Comment by itsjef** [comment] 2020-06-05 10:18
Thanks, I've changed the title and add more description.

**Comment by obfusk** [comment] 2020-06-06 21:11
Actually, I think it *is* a bug in postman. Looking at the example given in the postman bug report:

```
Content-Disposition: form-data; name="file"; filename="你好.xlsx"; filename*="UTF-8''%E4%BD%A0%E5%A5%BD.xlsx"
```

And looking at the relevant RFCs (https://tools.ietf.org/html/rfc6266 & https://tools.ietf.org/html/rfc5987), I notice that `filename*=` does not support `quoted-string` values -- only percent-encoding -- whereas the example combines both. When removing the non-RFC-compliant quotes, the example seems to work just fine with flask:

```
Content-Disposition: form-data; name="file"; filename="你好.xlsx"; filename*=UTF-8''%E4%BD%A0%E5%A5%BD.xlsx
```

**Comment by jab** [comment] 2020-06-06 22:15
Thanks @obfusk! @obfusk please report this back to Postman. Closing this issue out. If Flask (Werkzeug) is being less tolerant of non-spec-compliant input compared to other widely used HTTP parsers , maybe we can reconsider accepting a PR for this (and feel free to let us know whether you can reproduce this with Postman hitting other stacks). But the fact that Flask has been used by lots of international sites for many years presumably without this coming up until now suggests we’re probably okay leaving the current behavior as-is?

**Closed by jab** 2020-06-06 22:15 UTC
