### ISSUE TITLE
Typing issue with `redirect`

### ISSUE THREAD

**Issue by zx80** [pallets/flask#4612] opened 2022-05-27 07:47 UTC
Function `redirect` returns the wrong type according to `mypy`:

```python
# file "redir.py"
from flask import Response, redirect
def something() -> Response:
    return redirect("https://wikipedia.org/")
```

Then mypy complains:
```
redir.py:3: error: Incompatible return value type (got "werkzeug.wrappers.response.Response", expected "flask.wrappers.Response")
Found 1 error in 1 file (checked 1 source file)
```

Function `redirect` should return a `flask.wrappers.Response`.

Environment:

- Python version: 3.8.10
- Flask version: 2.1.2

**Comment by davidism** [comment] 2022-05-28 16:56
Duplicate of https://github.com/pallets/flask/issues/4600

**Closed by davidism** 2022-05-28 16:56 UTC
