### ISSUE TITLE
jQuery example and patterns/jquery document don't match

### ISSUE THREAD

**Issue by philomelus** [pallets/flask#4239] opened 2021-08-17 09:37 UTC
The patterns/jquery example shows using getJSON from jquery to do a get request.  I needed to do this via ajax/post, and it took me quite awhile to notice that the js_example in the flask repo DOES use ajax/post, even though the documentation says otherwise (and even refers to the js_example project in the git repo!).

To reproduce, look at the docs here:

https://flask.palletsprojects.com/en/latest/patterns/jquery/

and the code here (link from docs):

https://github.com/pallets/flask/tree/main/examples/javascript

- Python version: 3.9.6
- Flask version: 2.0.1

**Comment by ThiefMaster** [comment] 2021-08-17 09:41
Maybe we should just get rid of those examples? jQuery is no longer state of the art. `fetch()` does the job fine for HTTP requests; people should not add jQuery just to make requests in the background.

At the same time I think we could also get rid of the "plain XHR" example and polyfills for `fetch`. There are [no relevant browsers](https://caniuse.com/fetch) that do not have (native) fetch anymore.

**Comment by philomelus** [comment] 2021-08-17 21:56
jQuery may no longer be state of the art, but it is still used, and some of us still have old code to fix where we don't have the option (yet) to fix it the modern way.
Maybe changing the doc's to show the fetch way, and only mentioning that there is a jquery example in the repo would suffice (since it's mostly legacy at the moment, there isn't much point in explaining it).

**Comment by morebebop** [comment] 2022-01-22 00:19
I'm willing to make a pull request updating both the example code and the brief blurb beneath it in[ the documentation](https://flask.palletsprojects.com/en/latest/patterns/jquery/). It seems like a good beginner issue and this would be my first PR. Can I go ahead and make a pull request or does a maintainer have to chime in and approve first so it can be attached to the issue?

**Comment by davidism** [comment] 2022-01-22 00:25
No need to ask to work on an issue. As long as the issue is not assigned to anyone and doesn't have have a linked open PR (both can be seen in the sidebar), anyone is welcome to work on any issue.

**Closed** 2022-06-11 21:03 UTC
Labels: docs
