### ISSUE TITLE
The link for downloadable PDF documentation is not working

### ISSUE THREAD

**Issue by Itisfilipe** [pallets/flask#2455] opened 2017-08-28 00:07 UTC
I have tried to download the documentation in PDF from the official site (http://flask.pocoo.org/) and the link there (http://flask.pocoo.org/docs/0.12/.latex/Flask.pdf) is returning error 404.

**Comment by jacquerie** [comment] 2017-08-28 00:38
Duplicate of https://github.com/pallets/flask-docs/issues/3, and several others in this repo: https://github.com/pallets/flask/search?q=PDF&type=Issues&utf8=%E2%9C%93

**Closed** 2017-08-28 13:49 UTC
