### ISSUE TITLE
Tests failing on latest Flask version 2.2.1

### ISSUE THREAD

**Issue by hiteshgoyal18** [pallets/flask#4739] opened 2022-08-04 12:20 UTC
Hi All,
I am working on a Flask project and suddenly my unit tests start failing on the latest flask version `2.2.1`
Got following error while running [tox](https://pypi.org/project/tox/) command 

> /usr/lib/python3.8/doctest.py:939: in find
    self._find(tests, obj, name, module, source_lines, globs, {})
.tox/tests/lib/python3.8/site-packages/_pytest/doctest.py:533: in _find
    super()._find(  # type:ignore[misc]
/usr/lib/python3.8/doctest.py:998: in _find
    if ((inspect.isroutine(inspect.unwrap(val))
.tox/tests/lib/python3.8/site-packages/_pytest/doctest.py:475: in _mock_aware_unwrap
    return real_unwrap(func, stop=_is_mocked)
/usr/lib/python3.8/inspect.py:520: in unwrap
    while _is_wrapper(func):
/usr/lib/python3.8/inspect.py:514: in _is_wrapper
    return hasattr(f, '__wrapped__') and not stop(f)
.tox/tests/lib/python3.8/site-packages/werkzeug/local.py:316: in __get__
    obj = instance._get_current_object()  # type: ignore[misc]
.tox/tests/lib/python3.8/site-packages/werkzeug/local.py:509: in _get_current_object
    raise RuntimeError(unbound_message) from None
E   RuntimeError: Working outside of request context.
E   
E   This typically means that you attempted to use functionality that needed
E   an active HTTP request. Consult the documentation on testing for
E   information about how to avoid this problem.

When I changed my flask version back to `2.1.3` it started working again.

**Comment by hiteshgoyal18** [comment] 2022-08-04 12:51
Also, I am using latest version of `pytest 7.1.2`

**Comment by targhs** [comment] 2022-08-04 13:05
A small reproducible code sample will be appreciated

**Comment by davidism** [comment] 2022-08-04 13:08
Duplicate of https://github.com/pallets/werkzeug/issues/2485

**Closed by davidism** 2022-08-04 13:08 UTC
