### ISSUE TITLE
PROVIDE_AUTOMATIC_OPTIONS causes KeyError if not set

### ISSUE THREAD

**Issue by develerltd** [pallets/flask#5642] opened 2024-11-14 12:01 UTC
https://github.com/pallets/flask/blob/bc098406af9537aacc436cb2ea777fbc9ff4c5aa/src/flask/sansio/app.py#L641C12-L641C86

Simply changing this to : `self.config.get("PROVIDE_AUTOMATIC_OPTIONS", False)` should resolve the problem.

This change now released is causing upstream trouble in other packages such as Quart:
https://github.com/pallets/quart/issues/371

**Comment by davidism** [comment] 2024-11-14 15:25
Duplicate of pallets/quart#371

**Closed by davidism** 2024-11-14 15:25 UTC

**Comment by develerltd** [comment] 2024-11-14 15:26
This is not a duplicate as this is a separate project.

Anything that doesn't pin to flask 3.0.* will be broken by this change.

The fix is simple, as far as I am aware

**Comment by davidism** [comment] 2024-11-14 15:28
The pattern in Flask is that config is assumed to exist. There's already a PR opened in Quart so that that will be the case there as well. Nothing needs to change here.

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/

**Comment by davidism** [comment] 2024-11-14 16:55
Quart 0.19.9 is now available on PyPI.
