### ISSUE TITLE
better docs on message flashing and error handling in quickstart

### ISSUE THREAD

**Issue by wilsaj** [pallets/flask#426] opened 2012-03-12 03:33 UTC
unhappy user feedback: "Message Flashing and Error Handling are not explained well in the Quickstart section."

link: http://feedback.flask.pocoo.org/message/282

**Comment by jeffwidman** [comment] 2016-06-02 17:53
The feedback site now 404's, so it's not clear exactly what the problem is here. 

@wilsaj if you were the unhappy user, can you expand a little more on what you think should be added to the Quickstart to make it clearer?

For now, I'm closing since this is ancient issue, we'll re-open if we get more feedback.

**Closed by jeffwidman** 2016-06-02 17:53 UTC
