### ISSUE TITLE
Add 'python3 -m venv' information to the mod_wsgi docs

### ISSUE THREAD

**Issue by jonascj** [pallets/flask#2620] opened 2018-02-05 09:03 UTC
It would be nice if http://flask.pocoo.org/docs/0.12/deploying/mod_wsgi/ and hence `flask/docs/deploying/mod_wsgi.rst` sported some information on Python 3's venv virtual environment:

The information needed to deploy with `venv`is available here:

https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

Basically no `activate_this`-code is needed in the .wsgi file, just `WSGIDaemonProcess myapp python-home=/usr/local/venvs/myapp` in your httpd/apache config.

I'll draft something to merge if you think it is a good idea, otherwise this will have to serve as reference.

**Comment by davidism** [comment] 2018-02-05 12:44
I'd rather rewrite the whole thing to use current practices, if you want to contribute to that it would be welcome.

**Comment by jonascj** [comment] 2018-02-06 08:50
Good idea. So current practices could be Python 3.6 with `venv` and Apache 2.4?
The combinations are of course endless, many use nginx in place of Apache etc., but Apache seem to be the de facto standard when it comes to showing examples.

What about Python 2.7, should that still be included or should 2.7 users just be referred to older revisions of the docs?

**Comment by davidism** [comment] 2018-02-06 12:21
I mean whatever mod_wsgi says in its docs.

**Comment by jonascj** [comment] 2018-02-06 12:24
Alright, I'll give it a shot.

**Comment by davidism** [comment] 2018-02-23 23:58
Duplicate of #1948. Still open to PRs.

**Closed by davidism** 2018-02-23 23:58 UTC
Labels: docs

**Comment by jonascj** [comment] 2018-02-24 09:19
Fair, I'll submit something when I get round to it, no reason to keep this open.

**Comment by asciiascetic** [comment] 2018-02-26 01:23
I am most interested in up to date documentation on this.  Presently unable to deploy my app :/

**Comment by davidism** [comment] 2018-02-26 02:26
Up to date documentation can be found at the mod_wsgi docs. There is nothing flask specific to this.
