### ISSUE TITLE
HTTPStatus.BAD_REQUEST if don't access the body data

### ISSUE THREAD

**Issue by dontsovcmc** [pallets/flask#4532] opened 2022-04-11 22:03 UTC
Got error messages if don't access the body data in POST route. And I guess lost connection.

```
127.0.0.1 - - [12/Apr/2022 00:39:05] "POST /good HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2022 00:39:13] "POST /bad HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2022 00:39:13] code 400, message Bad HTTP/0.9 request type ('{"id":')
127.0.0.1 - - [12/Apr/2022 00:39:13] "None /bad HTTP/0.9" HTTPStatus.BAD_REQUEST -
```
Return data both good, but Bad route do something criminal

Example:
```
from flask import Flask, request
app = Flask(__name__)

@app.route('/bad', methods=['POST'])
def bad():
    return 'OK'

@app.route('/good', methods=['POST'])
def good():
    # j = request.get_json()  also works
    d = request.data
    return 'OK'

if __name__ == "__main__":
    app.run(host='127.0.0.1', port=8000, debug=True, use_reloader=False)
```

Request 1:
```
curl -X POST -H 'Content-Type: application/json' -H 'Connection: keep-alive' -d '{"id": "fo"}' http://127.0.0.1:8000/good -v
```

GOOD: no error messages in log
```
127.0.0.1 - - [12/Apr/2022 00:39:05] "POST /good HTTP/1.1" 200 -
```

Request 2:
```
curl -X POST -H 'Content-Type: application/json' -H 'Connection: keep-alive' -d '{"id": "fo"}' http://127.0.0.1:8000/bad -v
```

BAD: 
```
127.0.0.1 - - [12/Apr/2022 00:39:13] "POST /bad HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2022 00:39:13] code 400, message Bad HTTP/0.9 request type ('{"id":')
127.0.0.1 - - [12/Apr/2022 00:39:13] "None /bad HTTP/0.9" HTTPStatus.BAD_REQUEST -
```
Environment:

- Python version: 3.8.0
- Flask version: Flask 2.1.1, Werkzeug 2.1.1

**Comment by davidism** [comment] 2022-04-12 17:17
Duplicate of https://github.com/pallets/flask/issues/4507 and https://github.com/pallets/werkzeug/issues/2380

**Closed by davidism** 2022-04-12 17:17 UTC
