### ISSUE TITLE
Custom command for CLI does not raise import exceptions

### ISSUE THREAD

**Issue by darkclouder** [pallets/flask#3361] opened 2019-09-11 11:39 UTC
**Problem:**
Creating a custom command for the flask CLI with an import exception is silent, even when running the command, e.g. `start` with `flask start` directly.
This makes it difficult to debug import errors in changing environments, as you're left with
```
Error: No such command "start".
```
without further explanation.

**Origin:**
https://github.com/pallets/flask/blob/d694eb443a6243e248df974e9cd64defb591bf38/src/flask/cli.py#L541-L546
`NoAppException` is caught silently with a `pass`, even though `get_command` seems to only be used to execute a single command rather than an entire command listing.
However, even the command listing of `list_commands` explicitly prints the traceback with `traceback.print_exc()`.
Why that is not done in `get_command` is not clear to me at this point.

**Comment by davidism** [comment] 2019-10-12 16:50
Duplicate of #2741

**Closed by davidism** 2019-10-12 16:50 UTC

**Comment by darkclouder** [comment] 2019-10-15 14:31
The linked ticket has nothing to do with this issue. Please reopen.
Environment variables are set, this is regarding an import error within the app in the environment variable.

**Comment by darkclouder** [comment] 2019-11-06 09:38
@davidism please reopen.
