### ISSUE TITLE
jinja2 compiled templates not working

### ISSUE THREAD

**Issue by iljau** [pallets/flask#2883] opened 2018-08-10 22:03 UTC
### Expected Behavior

It should be possible to use jinja2 precompiled templates using loader shown in documentation: http://jinja.pocoo.org/docs/2.10/api/#jinja2.ModuleLoader

Sample repo: https://github.com/iljau/flask_precompiled_templates_issue

```python
from flask import Flask, render_template
from jinja2 import ChoiceLoader, FileSystemLoader, ModuleLoader

app = Flask(__name__)

app.jinja_env.compile_templates(
    target='templates_compiled', zip=None,
    ignore_errors=False
)

loader = ChoiceLoader([
    ModuleLoader('templates_compiled'),
    FileSystemLoader('templates')
])
app.jinja_loader = loader

@app.route('/')
def hello_world():
    return render_template("index.jinja2")


if __name__ == '__main__':
    app.run(debug=True)
```

### Actual Behavior

Tell us what happens instead.

```pytb
  File ..\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File ..\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Ilja\Code\flowers_v2\flowers\flowers_app.py", line 301, in general_expenses_list
    return render_template("general_expenses.jinja2", transactions=transactions, form=form)
  File ..\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File ..\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File ..\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File ..\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File ..\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File ..\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File ..\lib\site-packages\flask\templating.py", line 83, in _get_source_fast
    return loader.get_source(environment, template)
  File ..\lib\site-packages\jinja2\loaders.py", line 90, in get_source
    self.__class__.__name__)
RuntimeError: ModuleLoader cannot provide access to the source
```

### Environment

* Python version: 3.7.0
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by mrcz88** [comment] 2018-08-22 23:57
I have the same problem. Maybe, jinja2.loader.ModuleLoader should override get_source ?

**Comment by cldssty** [comment] 2018-08-28 11:00
https://github.com/pallets/jinja/blob/master/jinja2/loaders.py
Have noticed that in the ModuleLoader subclass,  `has_source_access = False`, which could be what's making the `get_source` implementation in the BaseLoader class raise the error you are seeing? 

Not sure why `has_source_access` is initialised to `False` there though.

**Comment by diofeher** [comment] 2018-10-03 14:54
If you set `has_source_access` to True in ModuleLoader it works. My question is: why this variable exists?

**Comment by diofeher** [comment] 2018-10-03 16:02
It looks the problem is on https://github.com/pallets/flask/blob/master/flask/templating.py#L47 `DispatchingJinjaLoader`, it will only try to use loaders with get_source implementation, thus not implementing ModuleLoader

**Comment by vuolter** [comment] 2018-10-21 02:12
See https://github.com/pallets/flask/issues/101 😞

**Comment by pernisunil** [comment] 2019-01-31 09:40
Is the issue "jinja2 compiled templates not working" resolved . I am still getting the same problem.
Can someone help me here

**Comment by zmwangx** [comment] 2019-05-13 11:15
I just encountered this problem. The solution is to override `app.jinja_env.loader` with `ModuleLoader` instead of `app.jinja_loader`.

The problem apparently arises when your `ModuleLoader` (or `ChoiceLoader`, or what have you) is being dispatched by `DispatchingJinjaLoader`, which assumes `get_source`, instead of operating on its own. Note that `DispatchingJinjaLoader` is only useful for integrating the base loader with all the blueprint loaders; if you already pre-compiled everything available to the `DispatchingJinjaLoader`, there's no point in dispatching anymore.

Basically, you can structure your application like this:

```py
import flask
import jinja2

app = flask.Flask(__name__)

# Make sure to import the blueprints before template compilation.
import blueprints.foo
import blueprints.bar

# Register filters and context processors before compilation, too.
@app.template_filter('foo')
def filter_foo(val):
    return val

@app.context_processor
def injector():
    return dict()

app.jinja_env.compile_templates('/path/to/compiled/templates')  # Of course this may be done separately.
app.jinja_env.loader = jinja2.ModuleLoader('/path/to/compiled/templates')
```

**Comment by davidism** [comment] 2019-06-27 23:52
I think the templating might be due for a general refactor at some point, it's definitely confusing that `app.jinja_loader`, `app.make_global_jinja_loader()`, and `app.jinja_env` are all different things that are interrelated in circuitous ways.

The `Flask.make_global_jinja_loader()` method is what you want to override. That gets assigned to `app.jinja_env.loader`. `app.jinja_loader` is used by the default global loader, so just replacing it doesn't replace the behavior of the global loader, which requires `get_source` for explaining the template loading chain during debugging.

Closing for now as there is an intended way to override this.

**Closed by davidism** 2019-06-27 23:52 UTC
