### ISSUE TITLE
Redirect from POST not working

### ISSUE THREAD

**Issue by object71** [pallets/flask#4557] opened 2022-04-28 16:49 UTC
When trying to redirect from a POST request to another page it seems that the request goes wrong. The redirect seems fine in the browser network debug tab and seems to pass normally from the POST method handling but when it tries to go to the new url it gets a status code of **|405 Method Not Allowed|**. The reason for this it seems by looking at the log is that the request gets mashed up with the query parameter somehow which seems like a bug:

![image](https://user-images.githubusercontent.com/19205853/165802744-4480c401-d772-47b8-802b-1aa7431cefa4.png)

Also it seems to work normally if there is no inputs in the form (but that is of no matter as there are no real life forms without any input).

Replication steps:

Happens on Edge, Chrome and Firefox for sure.

```python
from flask import Flask, request, redirect

app: Flask = Flask(__name__)

@app.route("/", methods=["GET"])
def hello():
    return "<a href='/my_form'>to form</a>"

@app.route("/my_form", methods=["GET", "POST"])
def my_form():
    if request.method == "GET":
        return "<form action='/my_form' method='POST' ><input type='hidden' name='id' value='0'><button type='submit'>Submit</button></form>"
    else:
        return redirect("/")

# app.run(host="127.0.0.1", port=80, debug=True)
```

I would expect that the submission of a form allows for a redirect to the home page without any errors like 405. I don't expect any of the arguments to be passed to the redirected request.

Environment:

- Python version: 3.9
- Flask version: 2.1.1

**Comment by davidism** [comment] 2022-04-28 16:50
Duplicate of https://github.com/pallets/flask/issues/4507, https://github.com/pallets/werkzeug/issues/2380, and many more. Be sure to check closed issues before opening a new one. Don't use the development server in production.

**Closed by davidism** 2022-04-28 16:50 UTC
